// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AttackHandler(ReducerEventContext ctx, ulong targetEntityId, uint skillDefId);
        public event AttackHandler? OnAttack;

        public void Attack(ulong targetEntityId, uint skillDefId)
        {
            conn.InternalCallReducer(new Reducer.Attack(targetEntityId, skillDefId));
        }

        public bool InvokeAttack(ReducerEventContext ctx, Reducer.Attack args)
        {
            if (OnAttack == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAttack(
                ctx,
                args.TargetEntityId,
                args.SkillDefId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class Attack : Reducer, IReducerArgs
        {
            [DataMember(Name = "target_entity_id")]
            public ulong TargetEntityId;
            [DataMember(Name = "skill_def_id")]
            public uint SkillDefId;

            public Attack(
                ulong TargetEntityId,
                uint SkillDefId
            )
            {
                this.TargetEntityId = TargetEntityId;
                this.SkillDefId = SkillDefId;
            }

            public Attack()
            {
            }

            string IReducerArgs.ReducerName => "attack";
        }
    }
}
