// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void CastSkillHandler(ReducerEventContext ctx, uint skillDefId, ulong targetEntityId);
        public event CastSkillHandler? OnCastSkill;

        public void CastSkill(uint skillDefId, ulong targetEntityId)
        {
            conn.InternalCallReducer(new Reducer.CastSkill(skillDefId, targetEntityId));
        }

        public bool InvokeCastSkill(ReducerEventContext ctx, Reducer.CastSkill args)
        {
            if (OnCastSkill == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnCastSkill(
                ctx,
                args.SkillDefId,
                args.TargetEntityId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class CastSkill : Reducer, IReducerArgs
        {
            [DataMember(Name = "skill_def_id")]
            public uint SkillDefId;
            [DataMember(Name = "target_entity_id")]
            public ulong TargetEntityId;

            public CastSkill(
                uint SkillDefId,
                ulong TargetEntityId
            )
            {
                this.SkillDefId = SkillDefId;
                this.TargetEntityId = TargetEntityId;
            }

            public CastSkill()
            {
            }

            string IReducerArgs.ReducerName => "cast_skill";
        }
    }
}
