// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void EquipItemHandler(ReducerEventContext ctx, ulong playerItemId);
        public event EquipItemHandler? OnEquipItem;

        public void EquipItem(ulong playerItemId)
        {
            conn.InternalCallReducer(new Reducer.EquipItem(playerItemId));
        }

        public bool InvokeEquipItem(ReducerEventContext ctx, Reducer.EquipItem args)
        {
            if (OnEquipItem == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnEquipItem(
                ctx,
                args.PlayerItemId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class EquipItem : Reducer, IReducerArgs
        {
            [DataMember(Name = "player_item_id")]
            public ulong PlayerItemId;

            public EquipItem(ulong PlayerItemId)
            {
                this.PlayerItemId = PlayerItemId;
            }

            public EquipItem()
            {
            }

            string IReducerArgs.ReducerName => "equip_item";
        }
    }
}
