// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void JoinGameHandler(ReducerEventContext ctx, SpacetimeDB.Types.PlayerClass classChoice);
        public event JoinGameHandler? OnJoinGame;

        public void JoinGame(SpacetimeDB.Types.PlayerClass classChoice)
        {
            conn.InternalCallReducer(new Reducer.JoinGame(classChoice));
        }

        public bool InvokeJoinGame(ReducerEventContext ctx, Reducer.JoinGame args)
        {
            if (OnJoinGame == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnJoinGame(
                ctx,
                args.ClassChoice
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class JoinGame : Reducer, IReducerArgs
        {
            [DataMember(Name = "class_choice")]
            public PlayerClass ClassChoice;

            public JoinGame(PlayerClass ClassChoice)
            {
                this.ClassChoice = ClassChoice;
            }

            public JoinGame()
            {
            }

            string IReducerArgs.ReducerName => "join_game";
        }
    }
}
