// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ResetEncounterHandler(ReducerEventContext ctx);
        public event ResetEncounterHandler? OnResetEncounter;

        public void ResetEncounter()
        {
            conn.InternalCallReducer(new Reducer.ResetEncounter());
        }

        public bool InvokeResetEncounter(ReducerEventContext ctx, Reducer.ResetEncounter args)
        {
            if (OnResetEncounter == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnResetEncounter(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ResetEncounter : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "reset_encounter";
        }
    }
}
