// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SubmitActionHandler(ReducerEventContext ctx, SpacetimeDB.Types.CombatActionType action, uint skillDefId, uint targetEnemyId, uint itemInstanceId);
        public event SubmitActionHandler? OnSubmitAction;

        public void SubmitAction(SpacetimeDB.Types.CombatActionType action, uint skillDefId, uint targetEnemyId, uint itemInstanceId)
        {
            conn.InternalCallReducer(new Reducer.SubmitAction(action, skillDefId, targetEnemyId, itemInstanceId));
        }

        public bool InvokeSubmitAction(ReducerEventContext ctx, Reducer.SubmitAction args)
        {
            if (OnSubmitAction == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSubmitAction(
                ctx,
                args.Action,
                args.SkillDefId,
                args.TargetEnemyId,
                args.ItemInstanceId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SubmitAction : Reducer, IReducerArgs
        {
            [DataMember(Name = "action")]
            public CombatActionType Action;
            [DataMember(Name = "skill_def_id")]
            public uint SkillDefId;
            [DataMember(Name = "target_enemy_id")]
            public uint TargetEnemyId;
            [DataMember(Name = "item_instance_id")]
            public uint ItemInstanceId;

            public SubmitAction(
                CombatActionType Action,
                uint SkillDefId,
                uint TargetEnemyId,
                uint ItemInstanceId
            )
            {
                this.Action = Action;
                this.SkillDefId = SkillDefId;
                this.TargetEnemyId = TargetEnemyId;
                this.ItemInstanceId = ItemInstanceId;
            }

            public SubmitAction()
            {
            }

            string IReducerArgs.ReducerName => "submit_action";
        }
    }
}
