// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UseItemHandler(ReducerEventContext ctx, SpacetimeDB.Types.ItemKind item);
        public event UseItemHandler? OnUseItem;

        public void UseItem(SpacetimeDB.Types.ItemKind item)
        {
            conn.InternalCallReducer(new Reducer.UseItem(item));
        }

        public bool InvokeUseItem(ReducerEventContext ctx, Reducer.UseItem args)
        {
            if (OnUseItem == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnUseItem(
                ctx,
                args.Item
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UseItem : Reducer, IReducerArgs
        {
            [DataMember(Name = "item")]
            public ItemKind Item;

            public UseItem(ItemKind Item)
            {
                this.Item = Item;
            }

            public UseItem()
            {
            }

            string IReducerArgs.ReducerName => "use_item";
        }
    }
}
