// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class BattleLogHandle : RemoteTableHandle<EventContext, BattleLog>
        {
            public override string RemoteTableName => "battle_log";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(BattleLog row) => row.Id;

                public IdUniqueIndex(BattleLogHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal BattleLogHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(BattleLog row) => row.Id;
        }

        public readonly BattleLogHandle BattleLog;
    }

    public sealed class BattleLogCols
    {
        public global::SpacetimeDB.Col<BattleLog, ulong> Id { get; }
        public global::SpacetimeDB.Col<BattleLog, uint> Round { get; }
        public global::SpacetimeDB.Col<BattleLog, string> Message { get; }
        public global::SpacetimeDB.Col<BattleLog, SpacetimeDB.Timestamp> CreatedAt { get; }

        public BattleLogCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<BattleLog, ulong>(tableName, "id");
            Round = new global::SpacetimeDB.Col<BattleLog, uint>(tableName, "round");
            Message = new global::SpacetimeDB.Col<BattleLog, string>(tableName, "message");
            CreatedAt = new global::SpacetimeDB.Col<BattleLog, SpacetimeDB.Timestamp>(tableName, "created_at");
        }
    }

    public sealed class BattleLogIxCols
    {
        public global::SpacetimeDB.IxCol<BattleLog, ulong> Id { get; }

        public BattleLogIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<BattleLog, ulong>(tableName, "id");
        }
    }
}
