// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class BossDropHandle : RemoteTableHandle<EventContext, BossDrop>
        {
            public override string RemoteTableName => "boss_drop";

            public sealed class IdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(BossDrop row) => row.Id;

                public IdUniqueIndex(BossDropHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class TierIndex : BTreeIndexBase<uint>
            {
                protected override uint GetKey(BossDrop row) => row.Tier;

                public TierIndex(BossDropHandle table) : base(table) { }
            }

            public readonly TierIndex Tier;

            internal BossDropHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                Tier = new(this);
            }

            protected override object GetPrimaryKey(BossDrop row) => row.Id;
        }

        public readonly BossDropHandle BossDrop;
    }

    public sealed class BossDropCols
    {
        public global::SpacetimeDB.Col<BossDrop, uint> Id { get; }
        public global::SpacetimeDB.Col<BossDrop, uint> Tier { get; }
        public global::SpacetimeDB.Col<BossDrop, uint> ItemDefId { get; }

        public BossDropCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<BossDrop, uint>(tableName, "id");
            Tier = new global::SpacetimeDB.Col<BossDrop, uint>(tableName, "tier");
            ItemDefId = new global::SpacetimeDB.Col<BossDrop, uint>(tableName, "item_def_id");
        }
    }

    public sealed class BossDropIxCols
    {
        public global::SpacetimeDB.IxCol<BossDrop, uint> Id { get; }
        public global::SpacetimeDB.IxCol<BossDrop, uint> Tier { get; }

        public BossDropIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<BossDrop, uint>(tableName, "id");
            Tier = new global::SpacetimeDB.IxCol<BossDrop, uint>(tableName, "tier");
        }
    }
}
