// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class CombatEventHandle : RemoteTableHandle<EventContext, CombatEvent>
        {
            public override string RemoteTableName => "combat_event";

            public sealed class IdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(CombatEvent row) => row.Id;

                public IdUniqueIndex(CombatEventHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal CombatEventHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);

            }

            protected override object GetPrimaryKey(CombatEvent row) => row.Id;
        }

        public readonly CombatEventHandle CombatEvent;
    }

    public sealed class CombatEventCols
    {
        public global::SpacetimeDB.Col<CombatEvent, uint> Id { get; }
        public global::SpacetimeDB.Col<CombatEvent, uint> Round { get; }
        public global::SpacetimeDB.Col<CombatEvent, ulong> ActorEntityId { get; }
        public global::SpacetimeDB.Col<CombatEvent, ulong> TargetEntityId { get; }
        public global::SpacetimeDB.Col<CombatEvent, CombatActionType> ActionType { get; }
        public global::SpacetimeDB.Col<CombatEvent, string> SkillName { get; }
        public global::SpacetimeDB.Col<CombatEvent, uint> Damage { get; }
        public global::SpacetimeDB.Col<CombatEvent, uint> Healing { get; }
        public global::SpacetimeDB.Col<CombatEvent, bool> Dodged { get; }
        public global::SpacetimeDB.Col<CombatEvent, bool> Clashed { get; }
        public global::SpacetimeDB.Col<CombatEvent, string> Message { get; }

        public CombatEventCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<CombatEvent, uint>(tableName, "id");
            Round = new global::SpacetimeDB.Col<CombatEvent, uint>(tableName, "round");
            ActorEntityId = new global::SpacetimeDB.Col<CombatEvent, ulong>(tableName, "actor_entity_id");
            TargetEntityId = new global::SpacetimeDB.Col<CombatEvent, ulong>(tableName, "target_entity_id");
            ActionType = new global::SpacetimeDB.Col<CombatEvent, CombatActionType>(tableName, "action_type");
            SkillName = new global::SpacetimeDB.Col<CombatEvent, string>(tableName, "skill_name");
            Damage = new global::SpacetimeDB.Col<CombatEvent, uint>(tableName, "damage");
            Healing = new global::SpacetimeDB.Col<CombatEvent, uint>(tableName, "healing");
            Dodged = new global::SpacetimeDB.Col<CombatEvent, bool>(tableName, "dodged");
            Clashed = new global::SpacetimeDB.Col<CombatEvent, bool>(tableName, "clashed");
            Message = new global::SpacetimeDB.Col<CombatEvent, string>(tableName, "message");
        }
    }

    public sealed class CombatEventIxCols
    {
        public global::SpacetimeDB.IxCol<CombatEvent, uint> Id { get; }

        public CombatEventIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<CombatEvent, uint>(tableName, "id");
        }
    }
}
