// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class EnemyHandle : RemoteTableHandle<EventContext, Enemy>
        {
            public override string RemoteTableName => "enemy";

            public sealed class IdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(Enemy row) => row.Id;

                public IdUniqueIndex(EnemyHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal EnemyHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(Enemy row) => row.Id;
        }

        public readonly EnemyHandle Enemy;
    }

    public sealed class EnemyCols
    {
        public global::SpacetimeDB.Col<Enemy, uint> Id { get; }
        public global::SpacetimeDB.Col<Enemy, uint> Slot { get; }
        public global::SpacetimeDB.Col<Enemy, string> Name { get; }
        public global::SpacetimeDB.Col<Enemy, uint> SpriteId { get; }
        public global::SpacetimeDB.Col<Enemy, Biome> Biome { get; }
        public global::SpacetimeDB.Col<Enemy, string> TraitName { get; }
        public global::SpacetimeDB.Col<Enemy, bool> IsBoss { get; }
        public global::SpacetimeDB.Col<Enemy, uint> Floor { get; }
        public global::SpacetimeDB.Col<Enemy, uint> MaxHealth { get; }
        public global::SpacetimeDB.Col<Enemy, uint> CurrHealth { get; }
        public global::SpacetimeDB.Col<Enemy, uint> MaxMana { get; }
        public global::SpacetimeDB.Col<Enemy, uint> CurrMana { get; }
        public global::SpacetimeDB.Col<Enemy, uint> Speed { get; }
        public global::SpacetimeDB.Col<Enemy, uint> Strength { get; }
        public global::SpacetimeDB.Col<Enemy, uint> Dexterity { get; }
        public global::SpacetimeDB.Col<Enemy, uint> Intelligence { get; }
        public global::SpacetimeDB.Col<Enemy, uint> Atk { get; }
        public global::SpacetimeDB.Col<Enemy, uint> Defense { get; }
        public global::SpacetimeDB.Col<Enemy, uint> StrengthBuff { get; }
        public global::SpacetimeDB.Col<Enemy, uint> NextTurnStrengthBonus { get; }
        public global::SpacetimeDB.Col<Enemy, uint> NextTurnSpeedOverride { get; }
        public global::SpacetimeDB.Col<Enemy, bool> GoFirstNextRound { get; }
        public global::SpacetimeDB.Col<Enemy, bool> Alive { get; }

        public EnemyCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<Enemy, uint>(tableName, "id");
            Slot = new global::SpacetimeDB.Col<Enemy, uint>(tableName, "slot");
            Name = new global::SpacetimeDB.Col<Enemy, string>(tableName, "name");
            SpriteId = new global::SpacetimeDB.Col<Enemy, uint>(tableName, "sprite_id");
            Biome = new global::SpacetimeDB.Col<Enemy, Biome>(tableName, "biome");
            TraitName = new global::SpacetimeDB.Col<Enemy, string>(tableName, "trait_name");
            IsBoss = new global::SpacetimeDB.Col<Enemy, bool>(tableName, "is_boss");
            Floor = new global::SpacetimeDB.Col<Enemy, uint>(tableName, "floor");
            MaxHealth = new global::SpacetimeDB.Col<Enemy, uint>(tableName, "max_health");
            CurrHealth = new global::SpacetimeDB.Col<Enemy, uint>(tableName, "curr_health");
            MaxMana = new global::SpacetimeDB.Col<Enemy, uint>(tableName, "max_mana");
            CurrMana = new global::SpacetimeDB.Col<Enemy, uint>(tableName, "curr_mana");
            Speed = new global::SpacetimeDB.Col<Enemy, uint>(tableName, "speed");
            Strength = new global::SpacetimeDB.Col<Enemy, uint>(tableName, "strength");
            Dexterity = new global::SpacetimeDB.Col<Enemy, uint>(tableName, "dexterity");
            Intelligence = new global::SpacetimeDB.Col<Enemy, uint>(tableName, "intelligence");
            Atk = new global::SpacetimeDB.Col<Enemy, uint>(tableName, "atk");
            Defense = new global::SpacetimeDB.Col<Enemy, uint>(tableName, "defense");
            StrengthBuff = new global::SpacetimeDB.Col<Enemy, uint>(tableName, "strength_buff");
            NextTurnStrengthBonus = new global::SpacetimeDB.Col<Enemy, uint>(tableName, "next_turn_strength_bonus");
            NextTurnSpeedOverride = new global::SpacetimeDB.Col<Enemy, uint>(tableName, "next_turn_speed_override");
            GoFirstNextRound = new global::SpacetimeDB.Col<Enemy, bool>(tableName, "go_first_next_round");
            Alive = new global::SpacetimeDB.Col<Enemy, bool>(tableName, "alive");
        }
    }

    public sealed class EnemyIxCols
    {
        public global::SpacetimeDB.IxCol<Enemy, uint> Id { get; }

        public EnemyIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<Enemy, uint>(tableName, "id");
        }
    }
}
