// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class EnemySkillHandle : RemoteTableHandle<EventContext, EnemySkill>
        {
            public override string RemoteTableName => "enemy_skill";

            public sealed class EnemyIdIndex : BTreeIndexBase<uint>
            {
                protected override uint GetKey(EnemySkill row) => row.EnemyId;

                public EnemyIdIndex(EnemySkillHandle table) : base(table) { }
            }

            public readonly EnemyIdIndex EnemyId;

            public sealed class IdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(EnemySkill row) => row.Id;

                public IdUniqueIndex(EnemySkillHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal EnemySkillHandle(DbConnection conn) : base(conn)
            {
                EnemyId = new(this);
                Id = new(this);
            }

            protected override object GetPrimaryKey(EnemySkill row) => row.Id;
        }

        public readonly EnemySkillHandle EnemySkill;
    }

    public sealed class EnemySkillCols
    {
        public global::SpacetimeDB.Col<EnemySkill, uint> Id { get; }
        public global::SpacetimeDB.Col<EnemySkill, uint> EnemyId { get; }
        public global::SpacetimeDB.Col<EnemySkill, uint> SkillDefId { get; }

        public EnemySkillCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<EnemySkill, uint>(tableName, "id");
            EnemyId = new global::SpacetimeDB.Col<EnemySkill, uint>(tableName, "enemy_id");
            SkillDefId = new global::SpacetimeDB.Col<EnemySkill, uint>(tableName, "skill_def_id");
        }
    }

    public sealed class EnemySkillIxCols
    {
        public global::SpacetimeDB.IxCol<EnemySkill, uint> Id { get; }
        public global::SpacetimeDB.IxCol<EnemySkill, uint> EnemyId { get; }

        public EnemySkillIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<EnemySkill, uint>(tableName, "id");
            EnemyId = new global::SpacetimeDB.IxCol<EnemySkill, uint>(tableName, "enemy_id");
        }
    }
}
