// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class EntityHandle : RemoteTableHandle<EventContext, Entity>
        {
            public override string RemoteTableName => "entity";

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(Entity row) => row.EntityId;

                public EntityIdUniqueIndex(EntityHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            internal EntityHandle(DbConnection conn) : base(conn)
            {
                EntityId = new(this);
            }

            protected override object GetPrimaryKey(Entity row) => row.EntityId;
        }

        public readonly EntityHandle Entity;
    }

    public sealed class EntityCols
    {
        public global::SpacetimeDB.Col<Entity, ulong> EntityId { get; }
        public global::SpacetimeDB.Col<Entity, Team> Faction { get; }
        public global::SpacetimeDB.Col<Entity, uint> Slot { get; }
        public global::SpacetimeDB.Col<Entity, string> Name { get; }
        public global::SpacetimeDB.Col<Entity, string> ClassName { get; }
        public global::SpacetimeDB.Col<Entity, int> MaxHp { get; }
        public global::SpacetimeDB.Col<Entity, int> Hp { get; }
        public global::SpacetimeDB.Col<Entity, int> MaxMana { get; }
        public global::SpacetimeDB.Col<Entity, int> Mana { get; }
        public global::SpacetimeDB.Col<Entity, int> BaseStrength { get; }
        public global::SpacetimeDB.Col<Entity, int> BaseDexterity { get; }
        public global::SpacetimeDB.Col<Entity, int> BaseIntelligence { get; }
        public global::SpacetimeDB.Col<Entity, int> BaseSpeed { get; }
        public global::SpacetimeDB.Col<Entity, int> Strength { get; }
        public global::SpacetimeDB.Col<Entity, int> Dexterity { get; }
        public global::SpacetimeDB.Col<Entity, int> Intelligence { get; }
        public global::SpacetimeDB.Col<Entity, int> Speed { get; }
        public global::SpacetimeDB.Col<Entity, int> Atk { get; }
        public global::SpacetimeDB.Col<Entity, int> Defense { get; }
        public global::SpacetimeDB.Col<Entity, int> StrengthBuff { get; }
        public global::SpacetimeDB.Col<Entity, int> NextTurnStrengthBonus { get; }
        public global::SpacetimeDB.Col<Entity, bool> GoFirstNextRound { get; }
        public global::SpacetimeDB.Col<Entity, bool> Alive { get; }
        public global::SpacetimeDB.Col<Entity, string> BasicAttackName { get; }
        public global::SpacetimeDB.Col<Entity, int> BurnStack { get; }
        public global::SpacetimeDB.Col<Entity, int> BurnCount { get; }
        public global::SpacetimeDB.Col<Entity, int> WeakStacks { get; }
        public global::SpacetimeDB.Col<Entity, int> NextTurnWeak { get; }
        public global::SpacetimeDB.Col<Entity, int> FragileStacks { get; }
        public global::SpacetimeDB.Col<Entity, int> NextTurnFragile { get; }
        public global::SpacetimeDB.Col<Entity, int> CombatSpeed { get; }
        public global::SpacetimeDB.Col<Entity, int> NextTurnSpeedSet { get; }
        public global::SpacetimeDB.Col<Entity, int> NextTurnSpeedDelta { get; }
        public global::SpacetimeDB.Col<Entity, int> DodgeBonusPercent { get; }
        public global::SpacetimeDB.Col<Entity, int> NextTurnDodgeBonus { get; }
        public global::SpacetimeDB.Col<Entity, int> EvadeThreshold { get; }
        public global::SpacetimeDB.Col<Entity, int> EvadeFragileOnDodge { get; }
        public global::SpacetimeDB.Col<Entity, int> EvadeStrengthOnDodge { get; }
        public global::SpacetimeDB.Col<Entity, bool> HasDodged { get; }
        public global::SpacetimeDB.Col<Entity, int> DodgeCount { get; }
        public global::SpacetimeDB.Col<Entity, bool> UsedAttackThisTurn { get; }
        public global::SpacetimeDB.Col<Entity, bool> UsedAttackLastTurn { get; }
        public global::SpacetimeDB.Col<Entity, int> NextAttackBonus { get; }
        public global::SpacetimeDB.Col<Entity, int> MagicBulletStage { get; }
        public global::SpacetimeDB.Col<Entity, int> SpearDiscount { get; }
        public global::SpacetimeDB.Col<Entity, int> VerticalCutDiscount { get; }
        public global::SpacetimeDB.Col<Entity, bool> FinishTheJobUsed { get; }
        public global::SpacetimeDB.Col<Entity, bool> FinishTheJobStance { get; }
        public global::SpacetimeDB.Col<Entity, int> FinishTheJobPower { get; }
        public global::SpacetimeDB.Col<Entity, bool> SkipNextTurn { get; }
        public global::SpacetimeDB.Col<Entity, bool> GrandUndertakingPending { get; }
        public global::SpacetimeDB.Col<Entity, string> VariantPrefix { get; }
        public global::SpacetimeDB.Col<Entity, int> TintR { get; }
        public global::SpacetimeDB.Col<Entity, int> TintG { get; }
        public global::SpacetimeDB.Col<Entity, int> TintB { get; }
        public global::SpacetimeDB.Col<Entity, bool> IsBoss { get; }
        public global::SpacetimeDB.Col<Entity, int> SkillCooldown { get; }
        public global::SpacetimeDB.Col<Entity, bool> DoubleStrength { get; }
        public global::SpacetimeDB.Col<Entity, bool> NextTurnDoubleStrength { get; }
        public global::SpacetimeDB.Col<Entity, int> TempHp { get; }

        public EntityCols(string tableName)
        {
            EntityId = new global::SpacetimeDB.Col<Entity, ulong>(tableName, "entity_id");
            Faction = new global::SpacetimeDB.Col<Entity, Team>(tableName, "faction");
            Slot = new global::SpacetimeDB.Col<Entity, uint>(tableName, "slot");
            Name = new global::SpacetimeDB.Col<Entity, string>(tableName, "name");
            ClassName = new global::SpacetimeDB.Col<Entity, string>(tableName, "class_name");
            MaxHp = new global::SpacetimeDB.Col<Entity, int>(tableName, "max_hp");
            Hp = new global::SpacetimeDB.Col<Entity, int>(tableName, "hp");
            MaxMana = new global::SpacetimeDB.Col<Entity, int>(tableName, "max_mana");
            Mana = new global::SpacetimeDB.Col<Entity, int>(tableName, "mana");
            BaseStrength = new global::SpacetimeDB.Col<Entity, int>(tableName, "base_strength");
            BaseDexterity = new global::SpacetimeDB.Col<Entity, int>(tableName, "base_dexterity");
            BaseIntelligence = new global::SpacetimeDB.Col<Entity, int>(tableName, "base_intelligence");
            BaseSpeed = new global::SpacetimeDB.Col<Entity, int>(tableName, "base_speed");
            Strength = new global::SpacetimeDB.Col<Entity, int>(tableName, "strength");
            Dexterity = new global::SpacetimeDB.Col<Entity, int>(tableName, "dexterity");
            Intelligence = new global::SpacetimeDB.Col<Entity, int>(tableName, "intelligence");
            Speed = new global::SpacetimeDB.Col<Entity, int>(tableName, "speed");
            Atk = new global::SpacetimeDB.Col<Entity, int>(tableName, "atk");
            Defense = new global::SpacetimeDB.Col<Entity, int>(tableName, "defense");
            StrengthBuff = new global::SpacetimeDB.Col<Entity, int>(tableName, "strength_buff");
            NextTurnStrengthBonus = new global::SpacetimeDB.Col<Entity, int>(tableName, "next_turn_strength_bonus");
            GoFirstNextRound = new global::SpacetimeDB.Col<Entity, bool>(tableName, "go_first_next_round");
            Alive = new global::SpacetimeDB.Col<Entity, bool>(tableName, "alive");
            BasicAttackName = new global::SpacetimeDB.Col<Entity, string>(tableName, "basic_attack_name");
            BurnStack = new global::SpacetimeDB.Col<Entity, int>(tableName, "burn_stack");
            BurnCount = new global::SpacetimeDB.Col<Entity, int>(tableName, "burn_count");
            WeakStacks = new global::SpacetimeDB.Col<Entity, int>(tableName, "weak_stacks");
            NextTurnWeak = new global::SpacetimeDB.Col<Entity, int>(tableName, "next_turn_weak");
            FragileStacks = new global::SpacetimeDB.Col<Entity, int>(tableName, "fragile_stacks");
            NextTurnFragile = new global::SpacetimeDB.Col<Entity, int>(tableName, "next_turn_fragile");
            CombatSpeed = new global::SpacetimeDB.Col<Entity, int>(tableName, "combat_speed");
            NextTurnSpeedSet = new global::SpacetimeDB.Col<Entity, int>(tableName, "next_turn_speed_set");
            NextTurnSpeedDelta = new global::SpacetimeDB.Col<Entity, int>(tableName, "next_turn_speed_delta");
            DodgeBonusPercent = new global::SpacetimeDB.Col<Entity, int>(tableName, "dodge_bonus_percent");
            NextTurnDodgeBonus = new global::SpacetimeDB.Col<Entity, int>(tableName, "next_turn_dodge_bonus");
            EvadeThreshold = new global::SpacetimeDB.Col<Entity, int>(tableName, "evade_threshold");
            EvadeFragileOnDodge = new global::SpacetimeDB.Col<Entity, int>(tableName, "evade_fragile_on_dodge");
            EvadeStrengthOnDodge = new global::SpacetimeDB.Col<Entity, int>(tableName, "evade_strength_on_dodge");
            HasDodged = new global::SpacetimeDB.Col<Entity, bool>(tableName, "has_dodged");
            DodgeCount = new global::SpacetimeDB.Col<Entity, int>(tableName, "dodge_count");
            UsedAttackThisTurn = new global::SpacetimeDB.Col<Entity, bool>(tableName, "used_attack_this_turn");
            UsedAttackLastTurn = new global::SpacetimeDB.Col<Entity, bool>(tableName, "used_attack_last_turn");
            NextAttackBonus = new global::SpacetimeDB.Col<Entity, int>(tableName, "next_attack_bonus");
            MagicBulletStage = new global::SpacetimeDB.Col<Entity, int>(tableName, "magic_bullet_stage");
            SpearDiscount = new global::SpacetimeDB.Col<Entity, int>(tableName, "spear_discount");
            VerticalCutDiscount = new global::SpacetimeDB.Col<Entity, int>(tableName, "vertical_cut_discount");
            FinishTheJobUsed = new global::SpacetimeDB.Col<Entity, bool>(tableName, "finish_the_job_used");
            FinishTheJobStance = new global::SpacetimeDB.Col<Entity, bool>(tableName, "finish_the_job_stance");
            FinishTheJobPower = new global::SpacetimeDB.Col<Entity, int>(tableName, "finish_the_job_power");
            SkipNextTurn = new global::SpacetimeDB.Col<Entity, bool>(tableName, "skip_next_turn");
            GrandUndertakingPending = new global::SpacetimeDB.Col<Entity, bool>(tableName, "grand_undertaking_pending");
            VariantPrefix = new global::SpacetimeDB.Col<Entity, string>(tableName, "variant_prefix");
            TintR = new global::SpacetimeDB.Col<Entity, int>(tableName, "tint_r");
            TintG = new global::SpacetimeDB.Col<Entity, int>(tableName, "tint_g");
            TintB = new global::SpacetimeDB.Col<Entity, int>(tableName, "tint_b");
            IsBoss = new global::SpacetimeDB.Col<Entity, bool>(tableName, "is_boss");
            SkillCooldown = new global::SpacetimeDB.Col<Entity, int>(tableName, "skill_cooldown");
            DoubleStrength = new global::SpacetimeDB.Col<Entity, bool>(tableName, "double_strength");
            NextTurnDoubleStrength = new global::SpacetimeDB.Col<Entity, bool>(tableName, "next_turn_double_strength");
            TempHp = new global::SpacetimeDB.Col<Entity, int>(tableName, "temp_hp");
        }
    }

    public sealed class EntityIxCols
    {
        public global::SpacetimeDB.IxCol<Entity, ulong> EntityId { get; }

        public EntityIxCols(string tableName)
        {
            EntityId = new global::SpacetimeDB.IxCol<Entity, ulong>(tableName, "entity_id");
        }
    }
}
