// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class EntityHandle : RemoteTableHandle<EventContext, Entity>
        {
            public override string RemoteTableName => "entity";

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(Entity row) => row.EntityId;

                public EntityIdUniqueIndex(EntityHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            internal EntityHandle(DbConnection conn) : base(conn)
            {
                EntityId = new(this);
            }

            protected override object GetPrimaryKey(Entity row) => row.EntityId;
        }

        public readonly EntityHandle Entity;
    }

    public sealed class EntityCols
    {
        public global::SpacetimeDB.Col<Entity, ulong> EntityId { get; }
        public global::SpacetimeDB.Col<Entity, Team> Faction { get; }
        public global::SpacetimeDB.Col<Entity, uint> Slot { get; }
        public global::SpacetimeDB.Col<Entity, string> Name { get; }
        public global::SpacetimeDB.Col<Entity, string> ClassName { get; }
        public global::SpacetimeDB.Col<Entity, int> MaxHp { get; }
        public global::SpacetimeDB.Col<Entity, int> Hp { get; }
        public global::SpacetimeDB.Col<Entity, int> MaxMana { get; }
        public global::SpacetimeDB.Col<Entity, int> Mana { get; }
        public global::SpacetimeDB.Col<Entity, int> Strength { get; }
        public global::SpacetimeDB.Col<Entity, int> Dexterity { get; }
        public global::SpacetimeDB.Col<Entity, int> Intelligence { get; }
        public global::SpacetimeDB.Col<Entity, int> Atk { get; }
        public global::SpacetimeDB.Col<Entity, int> Defense { get; }
        public global::SpacetimeDB.Col<Entity, int> Speed { get; }
        public global::SpacetimeDB.Col<Entity, bool> Alive { get; }
        public global::SpacetimeDB.Col<Entity, uint> StrengthBuff { get; }
        public global::SpacetimeDB.Col<Entity, uint> NextTurnStrengthBonus { get; }
        public global::SpacetimeDB.Col<Entity, uint> NextTurnSpeedOverride { get; }
        public global::SpacetimeDB.Col<Entity, bool> GoFirstNextRound { get; }

        public EntityCols(string tableName)
        {
            EntityId = new global::SpacetimeDB.Col<Entity, ulong>(tableName, "entity_id");
            Faction = new global::SpacetimeDB.Col<Entity, Team>(tableName, "faction");
            Slot = new global::SpacetimeDB.Col<Entity, uint>(tableName, "slot");
            Name = new global::SpacetimeDB.Col<Entity, string>(tableName, "name");
            ClassName = new global::SpacetimeDB.Col<Entity, string>(tableName, "class_name");
            MaxHp = new global::SpacetimeDB.Col<Entity, int>(tableName, "max_hp");
            Hp = new global::SpacetimeDB.Col<Entity, int>(tableName, "hp");
            MaxMana = new global::SpacetimeDB.Col<Entity, int>(tableName, "max_mana");
            Mana = new global::SpacetimeDB.Col<Entity, int>(tableName, "mana");
            Strength = new global::SpacetimeDB.Col<Entity, int>(tableName, "strength");
            Dexterity = new global::SpacetimeDB.Col<Entity, int>(tableName, "dexterity");
            Intelligence = new global::SpacetimeDB.Col<Entity, int>(tableName, "intelligence");
            Atk = new global::SpacetimeDB.Col<Entity, int>(tableName, "atk");
            Defense = new global::SpacetimeDB.Col<Entity, int>(tableName, "defense");
            Speed = new global::SpacetimeDB.Col<Entity, int>(tableName, "speed");
            Alive = new global::SpacetimeDB.Col<Entity, bool>(tableName, "alive");
            StrengthBuff = new global::SpacetimeDB.Col<Entity, uint>(tableName, "strength_buff");
            NextTurnStrengthBonus = new global::SpacetimeDB.Col<Entity, uint>(tableName, "next_turn_strength_bonus");
            NextTurnSpeedOverride = new global::SpacetimeDB.Col<Entity, uint>(tableName, "next_turn_speed_override");
            GoFirstNextRound = new global::SpacetimeDB.Col<Entity, bool>(tableName, "go_first_next_round");
        }
    }

    public sealed class EntityIxCols
    {
        public global::SpacetimeDB.IxCol<Entity, ulong> EntityId { get; }

        public EntityIxCols(string tableName)
        {
            EntityId = new global::SpacetimeDB.IxCol<Entity, ulong>(tableName, "entity_id");
        }
    }
}
