// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class EntitySkillHandle : RemoteTableHandle<EventContext, EntitySkill>
        {
            public override string RemoteTableName => "entity_skill";

            public sealed class EntityIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(EntitySkill row) => row.EntityId;

                public EntityIdIndex(EntitySkillHandle table) : base(table) { }
            }

            public readonly EntityIdIndex EntityId;

            public sealed class IdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(EntitySkill row) => row.Id;

                public IdUniqueIndex(EntitySkillHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal EntitySkillHandle(DbConnection conn) : base(conn)
            {
                EntityId = new(this);
                Id = new(this);
            }

            protected override object GetPrimaryKey(EntitySkill row) => row.Id;
        }

        public readonly EntitySkillHandle EntitySkill;
    }

    public sealed class EntitySkillCols
    {
        public global::SpacetimeDB.Col<EntitySkill, uint> Id { get; }
        public global::SpacetimeDB.Col<EntitySkill, ulong> EntityId { get; }
        public global::SpacetimeDB.Col<EntitySkill, uint> SkillDefId { get; }

        public EntitySkillCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<EntitySkill, uint>(tableName, "id");
            EntityId = new global::SpacetimeDB.Col<EntitySkill, ulong>(tableName, "entity_id");
            SkillDefId = new global::SpacetimeDB.Col<EntitySkill, uint>(tableName, "skill_def_id");
        }
    }

    public sealed class EntitySkillIxCols
    {
        public global::SpacetimeDB.IxCol<EntitySkill, uint> Id { get; }
        public global::SpacetimeDB.IxCol<EntitySkill, ulong> EntityId { get; }

        public EntitySkillIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<EntitySkill, uint>(tableName, "id");
            EntityId = new global::SpacetimeDB.IxCol<EntitySkill, ulong>(tableName, "entity_id");
        }
    }
}
