// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class GameSessionHandle : RemoteTableHandle<EventContext, GameSession>
        {
            public override string RemoteTableName => "game_session";

            public sealed class IdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(GameSession row) => row.Id;

                public IdUniqueIndex(GameSessionHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal GameSessionHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(GameSession row) => row.Id;
        }

        public readonly GameSessionHandle GameSession;
    }

    public sealed class GameSessionCols
    {
        public global::SpacetimeDB.Col<GameSession, uint> Id { get; }
        public global::SpacetimeDB.Col<GameSession, uint> PlayerCount { get; }
        public global::SpacetimeDB.Col<GameSession, uint> MaxPlayers { get; }
        public global::SpacetimeDB.Col<GameSession, GamePhase> Phase { get; }

        public GameSessionCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<GameSession, uint>(tableName, "id");
            PlayerCount = new global::SpacetimeDB.Col<GameSession, uint>(tableName, "player_count");
            MaxPlayers = new global::SpacetimeDB.Col<GameSession, uint>(tableName, "max_players");
            Phase = new global::SpacetimeDB.Col<GameSession, GamePhase>(tableName, "phase");
        }
    }

    public sealed class GameSessionIxCols
    {
        public global::SpacetimeDB.IxCol<GameSession, uint> Id { get; }

        public GameSessionIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<GameSession, uint>(tableName, "id");
        }
    }
}
