// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PendingRewardHandle : RemoteTableHandle<EventContext, PendingReward>
        {
            public override string RemoteTableName => "pending_reward";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(PendingReward row) => row.Id;

                public IdUniqueIndex(PendingRewardHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class OwnerIndex : BTreeIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(PendingReward row) => row.Owner;

                public OwnerIndex(PendingRewardHandle table) : base(table) { }
            }

            public readonly OwnerIndex Owner;

            internal PendingRewardHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                Owner = new(this);
            }

            protected override object GetPrimaryKey(PendingReward row) => row.Id;
        }

        public readonly PendingRewardHandle PendingReward;
    }

    public sealed class PendingRewardCols
    {
        public global::SpacetimeDB.Col<PendingReward, ulong> Id { get; }
        public global::SpacetimeDB.Col<PendingReward, SpacetimeDB.Identity> Owner { get; }
        public global::SpacetimeDB.Col<PendingReward, uint> ItemDefId { get; }

        public PendingRewardCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<PendingReward, ulong>(tableName, "id");
            Owner = new global::SpacetimeDB.Col<PendingReward, SpacetimeDB.Identity>(tableName, "owner");
            ItemDefId = new global::SpacetimeDB.Col<PendingReward, uint>(tableName, "item_def_id");
        }
    }

    public sealed class PendingRewardIxCols
    {
        public global::SpacetimeDB.IxCol<PendingReward, ulong> Id { get; }
        public global::SpacetimeDB.IxCol<PendingReward, SpacetimeDB.Identity> Owner { get; }

        public PendingRewardIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<PendingReward, ulong>(tableName, "id");
            Owner = new global::SpacetimeDB.IxCol<PendingReward, SpacetimeDB.Identity>(tableName, "owner");
        }
    }
}
