// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PlayerItemHandle : RemoteTableHandle<EventContext, PlayerItem>
        {
            public override string RemoteTableName => "player_item";

            public sealed class IdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(PlayerItem row) => row.Id;

                public IdUniqueIndex(PlayerItemHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class OwnerIndex : BTreeIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(PlayerItem row) => row.Owner;

                public OwnerIndex(PlayerItemHandle table) : base(table) { }
            }

            public readonly OwnerIndex Owner;

            internal PlayerItemHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                Owner = new(this);
            }

            protected override object GetPrimaryKey(PlayerItem row) => row.Id;
        }

        public readonly PlayerItemHandle PlayerItem;
    }

    public sealed class PlayerItemCols
    {
        public global::SpacetimeDB.Col<PlayerItem, uint> Id { get; }
        public global::SpacetimeDB.Col<PlayerItem, SpacetimeDB.Identity> Owner { get; }
        public global::SpacetimeDB.Col<PlayerItem, uint> ItemDefId { get; }
        public global::SpacetimeDB.Col<PlayerItem, uint> Quantity { get; }

        public PlayerItemCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<PlayerItem, uint>(tableName, "id");
            Owner = new global::SpacetimeDB.Col<PlayerItem, SpacetimeDB.Identity>(tableName, "owner");
            ItemDefId = new global::SpacetimeDB.Col<PlayerItem, uint>(tableName, "item_def_id");
            Quantity = new global::SpacetimeDB.Col<PlayerItem, uint>(tableName, "quantity");
        }
    }

    public sealed class PlayerItemIxCols
    {
        public global::SpacetimeDB.IxCol<PlayerItem, uint> Id { get; }
        public global::SpacetimeDB.IxCol<PlayerItem, SpacetimeDB.Identity> Owner { get; }

        public PlayerItemIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<PlayerItem, uint>(tableName, "id");
            Owner = new global::SpacetimeDB.IxCol<PlayerItem, SpacetimeDB.Identity>(tableName, "owner");
        }
    }
}
