// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PlayerSkillHandle : RemoteTableHandle<EventContext, PlayerSkill>
        {
            public override string RemoteTableName => "player_skill";

            public sealed class IdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(PlayerSkill row) => row.Id;

                public IdUniqueIndex(PlayerSkillHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class OwnerIndex : BTreeIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(PlayerSkill row) => row.Owner;

                public OwnerIndex(PlayerSkillHandle table) : base(table) { }
            }

            public readonly OwnerIndex Owner;

            internal PlayerSkillHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                Owner = new(this);
            }

            protected override object GetPrimaryKey(PlayerSkill row) => row.Id;
        }

        public readonly PlayerSkillHandle PlayerSkill;
    }

    public sealed class PlayerSkillCols
    {
        public global::SpacetimeDB.Col<PlayerSkill, uint> Id { get; }
        public global::SpacetimeDB.Col<PlayerSkill, SpacetimeDB.Identity> Owner { get; }
        public global::SpacetimeDB.Col<PlayerSkill, uint> SkillDefId { get; }
        public global::SpacetimeDB.Col<PlayerSkill, bool> Unlocked { get; }

        public PlayerSkillCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<PlayerSkill, uint>(tableName, "id");
            Owner = new global::SpacetimeDB.Col<PlayerSkill, SpacetimeDB.Identity>(tableName, "owner");
            SkillDefId = new global::SpacetimeDB.Col<PlayerSkill, uint>(tableName, "skill_def_id");
            Unlocked = new global::SpacetimeDB.Col<PlayerSkill, bool>(tableName, "unlocked");
        }
    }

    public sealed class PlayerSkillIxCols
    {
        public global::SpacetimeDB.IxCol<PlayerSkill, uint> Id { get; }
        public global::SpacetimeDB.IxCol<PlayerSkill, SpacetimeDB.Identity> Owner { get; }

        public PlayerSkillIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<PlayerSkill, uint>(tableName, "id");
            Owner = new global::SpacetimeDB.IxCol<PlayerSkill, SpacetimeDB.Identity>(tableName, "owner");
        }
    }
}
