// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PlayerHandle : RemoteTableHandle<EventContext, Player>
        {
            public override string RemoteTableName => "player";

            public sealed class IdentityUniqueIndex : UniqueIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(Player row) => row.Identity;

                public IdentityUniqueIndex(PlayerHandle table) : base(table) { }
            }

            public readonly IdentityUniqueIndex Identity;

            public sealed class SlotUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(Player row) => row.Slot;

                public SlotUniqueIndex(PlayerHandle table) : base(table) { }
            }

            public readonly SlotUniqueIndex Slot;

            internal PlayerHandle(DbConnection conn) : base(conn)
            {
                Identity = new(this);
                Slot = new(this);
            }

            protected override object GetPrimaryKey(Player row) => row.Identity;
        }

        public readonly PlayerHandle Player;
    }

    public sealed class PlayerCols
    {
        public global::SpacetimeDB.Col<Player, SpacetimeDB.Identity> Identity { get; }
        public global::SpacetimeDB.Col<Player, uint> Slot { get; }
        public global::SpacetimeDB.Col<Player, bool> Online { get; }
        public global::SpacetimeDB.Col<Player, PlayerClass> Class { get; }
        public global::SpacetimeDB.Col<Player, uint> MaxHealthPoints { get; }
        public global::SpacetimeDB.Col<Player, uint> CurrHealthPoints { get; }
        public global::SpacetimeDB.Col<Player, uint> MaxMana { get; }
        public global::SpacetimeDB.Col<Player, uint> CurrMana { get; }
        public global::SpacetimeDB.Col<Player, uint> Speed { get; }
        public global::SpacetimeDB.Col<Player, uint> Strength { get; }
        public global::SpacetimeDB.Col<Player, uint> Dexterity { get; }
        public global::SpacetimeDB.Col<Player, uint> Intelligence { get; }

        public PlayerCols(string tableName)
        {
            Identity = new global::SpacetimeDB.Col<Player, SpacetimeDB.Identity>(tableName, "identity");
            Slot = new global::SpacetimeDB.Col<Player, uint>(tableName, "slot");
            Online = new global::SpacetimeDB.Col<Player, bool>(tableName, "online");
            Class = new global::SpacetimeDB.Col<Player, PlayerClass>(tableName, "class");
            MaxHealthPoints = new global::SpacetimeDB.Col<Player, uint>(tableName, "max_health_points");
            CurrHealthPoints = new global::SpacetimeDB.Col<Player, uint>(tableName, "curr_health_points");
            MaxMana = new global::SpacetimeDB.Col<Player, uint>(tableName, "max_mana");
            CurrMana = new global::SpacetimeDB.Col<Player, uint>(tableName, "curr_mana");
            Speed = new global::SpacetimeDB.Col<Player, uint>(tableName, "speed");
            Strength = new global::SpacetimeDB.Col<Player, uint>(tableName, "strength");
            Dexterity = new global::SpacetimeDB.Col<Player, uint>(tableName, "dexterity");
            Intelligence = new global::SpacetimeDB.Col<Player, uint>(tableName, "intelligence");
        }
    }

    public sealed class PlayerIxCols
    {
        public global::SpacetimeDB.IxCol<Player, SpacetimeDB.Identity> Identity { get; }
        public global::SpacetimeDB.IxCol<Player, uint> Slot { get; }

        public PlayerIxCols(string tableName)
        {
            Identity = new global::SpacetimeDB.IxCol<Player, SpacetimeDB.Identity>(tableName, "identity");
            Slot = new global::SpacetimeDB.IxCol<Player, uint>(tableName, "slot");
        }
    }
}
