// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PlayerHandle : RemoteTableHandle<EventContext, Player>
        {
            public override string RemoteTableName => "player";

            public sealed class IdentityUniqueIndex : UniqueIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(Player row) => row.Identity;

                public IdentityUniqueIndex(PlayerHandle table) : base(table) { }
            }

            public readonly IdentityUniqueIndex Identity;

            public sealed class SlotUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(Player row) => row.Slot;

                public SlotUniqueIndex(PlayerHandle table) : base(table) { }
            }

            public readonly SlotUniqueIndex Slot;

            internal PlayerHandle(DbConnection conn) : base(conn)
            {
                Identity = new(this);
                Slot = new(this);
            }

            protected override object GetPrimaryKey(Player row) => row.Identity;
        }

        public readonly PlayerHandle Player;
    }

    public sealed class PlayerCols
    {
        public global::SpacetimeDB.Col<Player, SpacetimeDB.Identity> Identity { get; }
        public global::SpacetimeDB.Col<Player, uint> Slot { get; }
        public global::SpacetimeDB.Col<Player, bool> Online { get; }
        public global::SpacetimeDB.Col<Player, PlayerClass> Class { get; }
        public global::SpacetimeDB.Col<Player, string> Name { get; }
        public global::SpacetimeDB.Col<Player, uint> SpriteId { get; }
        public global::SpacetimeDB.Col<Player, uint> Level { get; }
        public global::SpacetimeDB.Col<Player, uint> Xp { get; }
        public global::SpacetimeDB.Col<Player, uint> UnspentStatPoints { get; }
        public global::SpacetimeDB.Col<Player, uint> MaxHealth { get; }
        public global::SpacetimeDB.Col<Player, uint> CurrHealth { get; }
        public global::SpacetimeDB.Col<Player, uint> MaxMana { get; }
        public global::SpacetimeDB.Col<Player, uint> CurrMana { get; }
        public global::SpacetimeDB.Col<Player, uint> Speed { get; }
        public global::SpacetimeDB.Col<Player, uint> Strength { get; }
        public global::SpacetimeDB.Col<Player, uint> Dexterity { get; }
        public global::SpacetimeDB.Col<Player, uint> Intelligence { get; }
        public global::SpacetimeDB.Col<Player, uint> BaseSpeed { get; }
        public global::SpacetimeDB.Col<Player, uint> BaseStrength { get; }
        public global::SpacetimeDB.Col<Player, uint> BaseDexterity { get; }
        public global::SpacetimeDB.Col<Player, uint> BaseIntelligence { get; }
        public global::SpacetimeDB.Col<Player, uint> Atk { get; }
        public global::SpacetimeDB.Col<Player, uint> BaseDefense { get; }
        public global::SpacetimeDB.Col<Player, uint> Defense { get; }
        public global::SpacetimeDB.Col<Player, uint> StrengthBuff { get; }
        public global::SpacetimeDB.Col<Player, uint> NextTurnStrengthBonus { get; }
        public global::SpacetimeDB.Col<Player, uint> NextTurnSpeedOverride { get; }
        public global::SpacetimeDB.Col<Player, bool> GoFirstNextRound { get; }
        public global::SpacetimeDB.Col<Player, bool> IsDefending { get; }
        public global::SpacetimeDB.Col<Player, bool> Alive { get; }
        public global::SpacetimeDB.Col<Player, uint> EquippedWeaponDefId { get; }
        public global::SpacetimeDB.Col<Player, uint> EquippedArmorDefId { get; }

        public PlayerCols(string tableName)
        {
            Identity = new global::SpacetimeDB.Col<Player, SpacetimeDB.Identity>(tableName, "identity");
            Slot = new global::SpacetimeDB.Col<Player, uint>(tableName, "slot");
            Online = new global::SpacetimeDB.Col<Player, bool>(tableName, "online");
            Class = new global::SpacetimeDB.Col<Player, PlayerClass>(tableName, "class");
            Name = new global::SpacetimeDB.Col<Player, string>(tableName, "name");
            SpriteId = new global::SpacetimeDB.Col<Player, uint>(tableName, "sprite_id");
            Level = new global::SpacetimeDB.Col<Player, uint>(tableName, "level");
            Xp = new global::SpacetimeDB.Col<Player, uint>(tableName, "xp");
            UnspentStatPoints = new global::SpacetimeDB.Col<Player, uint>(tableName, "unspent_stat_points");
            MaxHealth = new global::SpacetimeDB.Col<Player, uint>(tableName, "max_health");
            CurrHealth = new global::SpacetimeDB.Col<Player, uint>(tableName, "curr_health");
            MaxMana = new global::SpacetimeDB.Col<Player, uint>(tableName, "max_mana");
            CurrMana = new global::SpacetimeDB.Col<Player, uint>(tableName, "curr_mana");
            Speed = new global::SpacetimeDB.Col<Player, uint>(tableName, "speed");
            Strength = new global::SpacetimeDB.Col<Player, uint>(tableName, "strength");
            Dexterity = new global::SpacetimeDB.Col<Player, uint>(tableName, "dexterity");
            Intelligence = new global::SpacetimeDB.Col<Player, uint>(tableName, "intelligence");
            BaseSpeed = new global::SpacetimeDB.Col<Player, uint>(tableName, "base_speed");
            BaseStrength = new global::SpacetimeDB.Col<Player, uint>(tableName, "base_strength");
            BaseDexterity = new global::SpacetimeDB.Col<Player, uint>(tableName, "base_dexterity");
            BaseIntelligence = new global::SpacetimeDB.Col<Player, uint>(tableName, "base_intelligence");
            Atk = new global::SpacetimeDB.Col<Player, uint>(tableName, "atk");
            BaseDefense = new global::SpacetimeDB.Col<Player, uint>(tableName, "base_defense");
            Defense = new global::SpacetimeDB.Col<Player, uint>(tableName, "defense");
            StrengthBuff = new global::SpacetimeDB.Col<Player, uint>(tableName, "strength_buff");
            NextTurnStrengthBonus = new global::SpacetimeDB.Col<Player, uint>(tableName, "next_turn_strength_bonus");
            NextTurnSpeedOverride = new global::SpacetimeDB.Col<Player, uint>(tableName, "next_turn_speed_override");
            GoFirstNextRound = new global::SpacetimeDB.Col<Player, bool>(tableName, "go_first_next_round");
            IsDefending = new global::SpacetimeDB.Col<Player, bool>(tableName, "is_defending");
            Alive = new global::SpacetimeDB.Col<Player, bool>(tableName, "alive");
            EquippedWeaponDefId = new global::SpacetimeDB.Col<Player, uint>(tableName, "equipped_weapon_def_id");
            EquippedArmorDefId = new global::SpacetimeDB.Col<Player, uint>(tableName, "equipped_armor_def_id");
        }
    }

    public sealed class PlayerIxCols
    {
        public global::SpacetimeDB.IxCol<Player, SpacetimeDB.Identity> Identity { get; }
        public global::SpacetimeDB.IxCol<Player, uint> Slot { get; }

        public PlayerIxCols(string tableName)
        {
            Identity = new global::SpacetimeDB.IxCol<Player, SpacetimeDB.Identity>(tableName, "identity");
            Slot = new global::SpacetimeDB.IxCol<Player, uint>(tableName, "slot");
        }
    }
}
