// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class TurnOrderHandle : RemoteTableHandle<EventContext, TurnOrder>
        {
            public override string RemoteTableName => "turn_order";

            public sealed class IdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(TurnOrder row) => row.Id;

                public IdUniqueIndex(TurnOrderHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal TurnOrderHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(TurnOrder row) => row.Id;
        }

        public readonly TurnOrderHandle TurnOrder;
    }

    public sealed class TurnOrderCols
    {
        public global::SpacetimeDB.Col<TurnOrder, uint> Id { get; }
        public global::SpacetimeDB.Col<TurnOrder, uint> Sequence { get; }
        public global::SpacetimeDB.Col<TurnOrder, CombatantKind> Kind { get; }
        public global::SpacetimeDB.Col<TurnOrder, uint> CombatantId { get; }
        public global::SpacetimeDB.Col<TurnOrder, uint> Speed { get; }
        public global::SpacetimeDB.Col<TurnOrder, bool> HasActed { get; }
        public global::SpacetimeDB.Col<TurnOrder, bool> IsRush { get; }

        public TurnOrderCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<TurnOrder, uint>(tableName, "id");
            Sequence = new global::SpacetimeDB.Col<TurnOrder, uint>(tableName, "sequence");
            Kind = new global::SpacetimeDB.Col<TurnOrder, CombatantKind>(tableName, "kind");
            CombatantId = new global::SpacetimeDB.Col<TurnOrder, uint>(tableName, "combatant_id");
            Speed = new global::SpacetimeDB.Col<TurnOrder, uint>(tableName, "speed");
            HasActed = new global::SpacetimeDB.Col<TurnOrder, bool>(tableName, "has_acted");
            IsRush = new global::SpacetimeDB.Col<TurnOrder, bool>(tableName, "is_rush");
        }
    }

    public sealed class TurnOrderIxCols
    {
        public global::SpacetimeDB.IxCol<TurnOrder, uint> Id { get; }

        public TurnOrderIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<TurnOrder, uint>(tableName, "id");
        }
    }
}
