// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class BattleLog
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "round")]
        public uint Round;
        [DataMember(Name = "message")]
        public string Message;
        [DataMember(Name = "kind")]
        public LogKind Kind;
        [DataMember(Name = "actor_entity_id")]
        public ulong ActorEntityId;
        [DataMember(Name = "target_entity_id")]
        public ulong TargetEntityId;
        [DataMember(Name = "damage")]
        public int Damage;
        [DataMember(Name = "healing")]
        public int Healing;
        [DataMember(Name = "created_at")]
        public SpacetimeDB.Timestamp CreatedAt;

        public BattleLog(
            ulong Id,
            uint Round,
            string Message,
            LogKind Kind,
            ulong ActorEntityId,
            ulong TargetEntityId,
            int Damage,
            int Healing,
            SpacetimeDB.Timestamp CreatedAt
        )
        {
            this.Id = Id;
            this.Round = Round;
            this.Message = Message;
            this.Kind = Kind;
            this.ActorEntityId = ActorEntityId;
            this.TargetEntityId = TargetEntityId;
            this.Damage = Damage;
            this.Healing = Healing;
            this.CreatedAt = CreatedAt;
        }

        public BattleLog()
        {
            this.Message = "";
        }
    }
}
