// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class BiomeDef
    {
        [DataMember(Name = "id")]
        public uint Id;
        [DataMember(Name = "kind")]
        public WorldBiome Kind;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "the_name")]
        public string TheName;
        [DataMember(Name = "back_top_r")]
        public int BackTopR;
        [DataMember(Name = "back_top_g")]
        public int BackTopG;
        [DataMember(Name = "back_top_b")]
        public int BackTopB;
        [DataMember(Name = "back_bot_r")]
        public int BackBotR;
        [DataMember(Name = "back_bot_g")]
        public int BackBotG;
        [DataMember(Name = "back_bot_b")]
        public int BackBotB;
        [DataMember(Name = "variant_prefix")]
        public string VariantPrefix;
        [DataMember(Name = "tint_r")]
        public int TintR;
        [DataMember(Name = "tint_g")]
        public int TintG;
        [DataMember(Name = "tint_b")]
        public int TintB;

        public BiomeDef(
            uint Id,
            WorldBiome Kind,
            string Name,
            string TheName,
            int BackTopR,
            int BackTopG,
            int BackTopB,
            int BackBotR,
            int BackBotG,
            int BackBotB,
            string VariantPrefix,
            int TintR,
            int TintG,
            int TintB
        )
        {
            this.Id = Id;
            this.Kind = Kind;
            this.Name = Name;
            this.TheName = TheName;
            this.BackTopR = BackTopR;
            this.BackTopG = BackTopG;
            this.BackTopB = BackTopB;
            this.BackBotR = BackBotR;
            this.BackBotG = BackBotG;
            this.BackBotB = BackBotB;
            this.VariantPrefix = VariantPrefix;
            this.TintR = TintR;
            this.TintG = TintG;
            this.TintB = TintB;
        }

        public BiomeDef()
        {
            this.Name = "";
            this.TheName = "";
            this.VariantPrefix = "";
        }
    }
}
