// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class CombatEvent
    {
        [DataMember(Name = "id")]
        public uint Id;
        [DataMember(Name = "round")]
        public uint Round;
        [DataMember(Name = "actor_entity_id")]
        public ulong ActorEntityId;
        [DataMember(Name = "target_entity_id")]
        public ulong TargetEntityId;
        [DataMember(Name = "action_type")]
        public CombatActionType ActionType;
        [DataMember(Name = "skill_name")]
        public string SkillName;
        [DataMember(Name = "damage")]
        public uint Damage;
        [DataMember(Name = "healing")]
        public uint Healing;
        [DataMember(Name = "dodged")]
        public bool Dodged;
        [DataMember(Name = "clashed")]
        public bool Clashed;
        [DataMember(Name = "message")]
        public string Message;

        public CombatEvent(
            uint Id,
            uint Round,
            ulong ActorEntityId,
            ulong TargetEntityId,
            CombatActionType ActionType,
            string SkillName,
            uint Damage,
            uint Healing,
            bool Dodged,
            bool Clashed,
            string Message
        )
        {
            this.Id = Id;
            this.Round = Round;
            this.ActorEntityId = ActorEntityId;
            this.TargetEntityId = TargetEntityId;
            this.ActionType = ActionType;
            this.SkillName = SkillName;
            this.Damage = Damage;
            this.Healing = Healing;
            this.Dodged = Dodged;
            this.Clashed = Clashed;
            this.Message = Message;
        }

        public CombatEvent()
        {
            this.SkillName = "";
            this.Message = "";
        }
    }
}
