// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Entity
    {
        [DataMember(Name = "entity_id")]
        public ulong EntityId;
        [DataMember(Name = "faction")]
        public Team Faction;
        [DataMember(Name = "slot")]
        public uint Slot;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "class_name")]
        public string ClassName;
        [DataMember(Name = "max_hp")]
        public int MaxHp;
        [DataMember(Name = "hp")]
        public int Hp;
        [DataMember(Name = "max_mana")]
        public int MaxMana;
        [DataMember(Name = "mana")]
        public int Mana;
        [DataMember(Name = "strength")]
        public int Strength;
        [DataMember(Name = "dexterity")]
        public int Dexterity;
        [DataMember(Name = "intelligence")]
        public int Intelligence;
        [DataMember(Name = "atk")]
        public int Atk;
        [DataMember(Name = "defense")]
        public int Defense;
        [DataMember(Name = "speed")]
        public int Speed;
        [DataMember(Name = "alive")]
        public bool Alive;
        [DataMember(Name = "strength_buff")]
        public uint StrengthBuff;
        [DataMember(Name = "next_turn_strength_bonus")]
        public uint NextTurnStrengthBonus;
        [DataMember(Name = "next_turn_speed_override")]
        public uint NextTurnSpeedOverride;
        [DataMember(Name = "go_first_next_round")]
        public bool GoFirstNextRound;

        public Entity(
            ulong EntityId,
            Team Faction,
            uint Slot,
            string Name,
            string ClassName,
            int MaxHp,
            int Hp,
            int MaxMana,
            int Mana,
            int Strength,
            int Dexterity,
            int Intelligence,
            int Atk,
            int Defense,
            int Speed,
            bool Alive,
            uint StrengthBuff,
            uint NextTurnStrengthBonus,
            uint NextTurnSpeedOverride,
            bool GoFirstNextRound
        )
        {
            this.EntityId = EntityId;
            this.Faction = Faction;
            this.Slot = Slot;
            this.Name = Name;
            this.ClassName = ClassName;
            this.MaxHp = MaxHp;
            this.Hp = Hp;
            this.MaxMana = MaxMana;
            this.Mana = Mana;
            this.Strength = Strength;
            this.Dexterity = Dexterity;
            this.Intelligence = Intelligence;
            this.Atk = Atk;
            this.Defense = Defense;
            this.Speed = Speed;
            this.Alive = Alive;
            this.StrengthBuff = StrengthBuff;
            this.NextTurnStrengthBonus = NextTurnStrengthBonus;
            this.NextTurnSpeedOverride = NextTurnSpeedOverride;
            this.GoFirstNextRound = GoFirstNextRound;
        }

        public Entity()
        {
            this.Name = "";
            this.ClassName = "";
        }
    }
}
