// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ItemDef
    {
        [DataMember(Name = "id")]
        public uint Id;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "short_name")]
        public string ShortName;
        [DataMember(Name = "kind")]
        public ItemKind Kind;
        [DataMember(Name = "weapon_type")]
        public WeaponType WeaponType;
        [DataMember(Name = "atk_bonus")]
        public int AtkBonus;
        [DataMember(Name = "defense_bonus")]
        public int DefenseBonus;
        [DataMember(Name = "strength_bonus")]
        public int StrengthBonus;
        [DataMember(Name = "dexterity_bonus")]
        public int DexterityBonus;
        [DataMember(Name = "intelligence_bonus")]
        public int IntelligenceBonus;
        [DataMember(Name = "speed_bonus")]
        public int SpeedBonus;
        [DataMember(Name = "max_hp_bonus")]
        public int MaxHpBonus;
        [DataMember(Name = "max_mana_bonus")]
        public int MaxManaBonus;
        [DataMember(Name = "heal_amount")]
        public int HealAmount;
        [DataMember(Name = "mana_restore_amount")]
        public int ManaRestoreAmount;
        [DataMember(Name = "description")]
        public string Description;

        public ItemDef(
            uint Id,
            string Name,
            string ShortName,
            ItemKind Kind,
            WeaponType WeaponType,
            int AtkBonus,
            int DefenseBonus,
            int StrengthBonus,
            int DexterityBonus,
            int IntelligenceBonus,
            int SpeedBonus,
            int MaxHpBonus,
            int MaxManaBonus,
            int HealAmount,
            int ManaRestoreAmount,
            string Description
        )
        {
            this.Id = Id;
            this.Name = Name;
            this.ShortName = ShortName;
            this.Kind = Kind;
            this.WeaponType = WeaponType;
            this.AtkBonus = AtkBonus;
            this.DefenseBonus = DefenseBonus;
            this.StrengthBonus = StrengthBonus;
            this.DexterityBonus = DexterityBonus;
            this.IntelligenceBonus = IntelligenceBonus;
            this.SpeedBonus = SpeedBonus;
            this.MaxHpBonus = MaxHpBonus;
            this.MaxManaBonus = MaxManaBonus;
            this.HealAmount = HealAmount;
            this.ManaRestoreAmount = ManaRestoreAmount;
            this.Description = Description;
        }

        public ItemDef()
        {
            this.Name = "";
            this.ShortName = "";
            this.Description = "";
        }
    }
}
