// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Player
    {
        [DataMember(Name = "identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "slot")]
        public uint Slot;
        [DataMember(Name = "online")]
        public bool Online;
        [DataMember(Name = "class")]
        public PlayerClass Class;
        [DataMember(Name = "entity_id")]
        public ulong EntityId;
        [DataMember(Name = "ready")]
        public bool Ready;

        public Player(
            SpacetimeDB.Identity Identity,
            uint Slot,
            bool Online,
            PlayerClass Class,
            ulong EntityId,
            bool Ready
        )
        {
            this.Identity = Identity;
            this.Slot = Slot;
            this.Online = Online;
            this.Class = Class;
            this.EntityId = EntityId;
            this.Ready = Ready;
        }

        public Player()
        {
        }
    }
}
