// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PlayerSkill
    {
        [DataMember(Name = "id")]
        public uint Id;
        [DataMember(Name = "owner")]
        public SpacetimeDB.Identity Owner;
        [DataMember(Name = "skill_def_id")]
        public uint SkillDefId;
        [DataMember(Name = "unlocked")]
        public bool Unlocked;

        public PlayerSkill(
            uint Id,
            SpacetimeDB.Identity Owner,
            uint SkillDefId,
            bool Unlocked
        )
        {
            this.Id = Id;
            this.Owner = Owner;
            this.SkillDefId = SkillDefId;
            this.Unlocked = Unlocked;
        }

        public PlayerSkill()
        {

        }
    }
}
