// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class SkillDef
    {
        [DataMember(Name = "id")]
        public uint Id;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "is_enemy_skill")]
        public bool IsEnemySkill;
        [DataMember(Name = "for_class")]
        public PlayerClass ForClass;
        [DataMember(Name = "mana_cost")]
        public int ManaCost;
        [DataMember(Name = "base_damage")]
        public int BaseDamage;
        [DataMember(Name = "target_count")]
        public int TargetCount;
        [DataMember(Name = "always_go_first")]
        public bool AlwaysGoFirst;
        [DataMember(Name = "next_turn_strength_bonus")]
        public int NextTurnStrengthBonus;
        [DataMember(Name = "damage_type")]
        public DamageType DamageType;

        public SkillDef(
            uint Id,
            string Name,
            bool IsEnemySkill,
            PlayerClass ForClass,
            int ManaCost,
            int BaseDamage,
            int TargetCount,
            bool AlwaysGoFirst,
            int NextTurnStrengthBonus,
            DamageType DamageType
        )
        {
            this.Id = Id;
            this.Name = Name;
            this.IsEnemySkill = IsEnemySkill;
            this.ForClass = ForClass;
            this.ManaCost = ManaCost;
            this.BaseDamage = BaseDamage;
            this.TargetCount = TargetCount;
            this.AlwaysGoFirst = AlwaysGoFirst;
            this.NextTurnStrengthBonus = NextTurnStrengthBonus;
            this.DamageType = DamageType;
        }

        public SkillDef()
        {
            this.Name = "";
        }
    }
}
