// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class TurnOrder
    {
        [DataMember(Name = "idx")]
        public uint Idx;
        [DataMember(Name = "entity_id")]
        public ulong EntityId;
        [DataMember(Name = "speed")]
        public uint Speed;
        [DataMember(Name = "has_acted")]
        public bool HasActed;
        [DataMember(Name = "is_rush")]
        public bool IsRush;

        public TurnOrder(
            uint Idx,
            ulong EntityId,
            uint Speed,
            bool HasActed,
            bool IsRush
        )
        {
            this.Idx = Idx;
            this.EntityId = EntityId;
            this.Speed = Speed;
            this.HasActed = HasActed;
            this.IsRush = IsRush;
        }

        public TurnOrder()
        {
        }
    }
}
