// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class BiomeDefHandle : RemoteTableHandle<EventContext, BiomeDef>
        {
            public override string RemoteTableName => "biome_def";

            public sealed class IdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(BiomeDef row) => row.Id;

                public IdUniqueIndex(BiomeDefHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal BiomeDefHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(BiomeDef row) => row.Id;
        }

        public readonly BiomeDefHandle BiomeDef;
    }

    public sealed class BiomeDefCols
    {
        public global::SpacetimeDB.Col<BiomeDef, uint> Id { get; }
        public global::SpacetimeDB.Col<BiomeDef, WorldBiome> Kind { get; }
        public global::SpacetimeDB.Col<BiomeDef, string> Name { get; }
        public global::SpacetimeDB.Col<BiomeDef, string> TheName { get; }
        public global::SpacetimeDB.Col<BiomeDef, int> BackTopR { get; }
        public global::SpacetimeDB.Col<BiomeDef, int> BackTopG { get; }
        public global::SpacetimeDB.Col<BiomeDef, int> BackTopB { get; }
        public global::SpacetimeDB.Col<BiomeDef, int> BackBotR { get; }
        public global::SpacetimeDB.Col<BiomeDef, int> BackBotG { get; }
        public global::SpacetimeDB.Col<BiomeDef, int> BackBotB { get; }
        public global::SpacetimeDB.Col<BiomeDef, string> VariantPrefix { get; }
        public global::SpacetimeDB.Col<BiomeDef, int> TintR { get; }
        public global::SpacetimeDB.Col<BiomeDef, int> TintG { get; }
        public global::SpacetimeDB.Col<BiomeDef, int> TintB { get; }

        public BiomeDefCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<BiomeDef, uint>(tableName, "id");
            Kind = new global::SpacetimeDB.Col<BiomeDef, WorldBiome>(tableName, "kind");
            Name = new global::SpacetimeDB.Col<BiomeDef, string>(tableName, "name");
            TheName = new global::SpacetimeDB.Col<BiomeDef, string>(tableName, "the_name");
            BackTopR = new global::SpacetimeDB.Col<BiomeDef, int>(tableName, "back_top_r");
            BackTopG = new global::SpacetimeDB.Col<BiomeDef, int>(tableName, "back_top_g");
            BackTopB = new global::SpacetimeDB.Col<BiomeDef, int>(tableName, "back_top_b");
            BackBotR = new global::SpacetimeDB.Col<BiomeDef, int>(tableName, "back_bot_r");
            BackBotG = new global::SpacetimeDB.Col<BiomeDef, int>(tableName, "back_bot_g");
            BackBotB = new global::SpacetimeDB.Col<BiomeDef, int>(tableName, "back_bot_b");
            VariantPrefix = new global::SpacetimeDB.Col<BiomeDef, string>(tableName, "variant_prefix");
            TintR = new global::SpacetimeDB.Col<BiomeDef, int>(tableName, "tint_r");
            TintG = new global::SpacetimeDB.Col<BiomeDef, int>(tableName, "tint_g");
            TintB = new global::SpacetimeDB.Col<BiomeDef, int>(tableName, "tint_b");
        }
    }

    public sealed class BiomeDefIxCols
    {
        public global::SpacetimeDB.IxCol<BiomeDef, uint> Id { get; }

        public BiomeDefIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<BiomeDef, uint>(tableName, "id");
        }
    }
}
