// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class GameSessionHandle : RemoteTableHandle<EventContext, GameSession>
        {
            public override string RemoteTableName => "game_session";

            public sealed class IdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(GameSession row) => row.Id;

                public IdUniqueIndex(GameSessionHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal GameSessionHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(GameSession row) => row.Id;
        }

        public readonly GameSessionHandle GameSession;
    }

    public sealed class GameSessionCols
    {
        public global::SpacetimeDB.Col<GameSession, uint> Id { get; }
        public global::SpacetimeDB.Col<GameSession, uint> PlayerCount { get; }
        public global::SpacetimeDB.Col<GameSession, uint> MaxPlayers { get; }
        public global::SpacetimeDB.Col<GameSession, BattlePhase> Phase { get; }
        public global::SpacetimeDB.Col<GameSession, uint> Round { get; }
        public global::SpacetimeDB.Col<GameSession, uint> TurnIndex { get; }
        public global::SpacetimeDB.Col<GameSession, ulong> ActiveEntityId { get; }
        public global::SpacetimeDB.Col<GameSession, uint> StageNumber { get; }
        public global::SpacetimeDB.Col<GameSession, bool> UpcomingRestStop { get; }
        public global::SpacetimeDB.Col<GameSession, ulong> AttackRedirectEntityId { get; }
        public global::SpacetimeDB.Col<GameSession, WorldBiome> CurrentBiome { get; }
        public global::SpacetimeDB.Col<GameSession, WorldBiome> NextBiome { get; }
        public global::SpacetimeDB.Col<GameSession, bool> IsBossStage { get; }
        public global::SpacetimeDB.Col<GameSession, bool> BossLootGranted { get; }
        public global::SpacetimeDB.Col<GameSession, string> StageClearNote { get; }
        public global::SpacetimeDB.Col<GameSession, bool> RestAmuletGranted { get; }

        public GameSessionCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<GameSession, uint>(tableName, "id");
            PlayerCount = new global::SpacetimeDB.Col<GameSession, uint>(tableName, "player_count");
            MaxPlayers = new global::SpacetimeDB.Col<GameSession, uint>(tableName, "max_players");
            Phase = new global::SpacetimeDB.Col<GameSession, BattlePhase>(tableName, "phase");
            Round = new global::SpacetimeDB.Col<GameSession, uint>(tableName, "round");
            TurnIndex = new global::SpacetimeDB.Col<GameSession, uint>(tableName, "turn_index");
            ActiveEntityId = new global::SpacetimeDB.Col<GameSession, ulong>(tableName, "active_entity_id");
            StageNumber = new global::SpacetimeDB.Col<GameSession, uint>(tableName, "stage_number");
            UpcomingRestStop = new global::SpacetimeDB.Col<GameSession, bool>(tableName, "upcoming_rest_stop");
            AttackRedirectEntityId = new global::SpacetimeDB.Col<GameSession, ulong>(tableName, "attack_redirect_entity_id");
            CurrentBiome = new global::SpacetimeDB.Col<GameSession, WorldBiome>(tableName, "current_biome");
            NextBiome = new global::SpacetimeDB.Col<GameSession, WorldBiome>(tableName, "next_biome");
            IsBossStage = new global::SpacetimeDB.Col<GameSession, bool>(tableName, "is_boss_stage");
            BossLootGranted = new global::SpacetimeDB.Col<GameSession, bool>(tableName, "boss_loot_granted");
            StageClearNote = new global::SpacetimeDB.Col<GameSession, string>(tableName, "stage_clear_note");
            RestAmuletGranted = new global::SpacetimeDB.Col<GameSession, bool>(tableName, "rest_amulet_granted");
        }
    }

    public sealed class GameSessionIxCols
    {
        public global::SpacetimeDB.IxCol<GameSession, uint> Id { get; }

        public GameSessionIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<GameSession, uint>(tableName, "id");
        }
    }
}
