// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ItemDefHandle : RemoteTableHandle<EventContext, ItemDef>
        {
            public override string RemoteTableName => "item_def";

            public sealed class IdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(ItemDef row) => row.Id;

                public IdUniqueIndex(ItemDefHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal ItemDefHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(ItemDef row) => row.Id;
        }

        public readonly ItemDefHandle ItemDef;
    }

    public sealed class ItemDefCols
    {
        public global::SpacetimeDB.Col<ItemDef, uint> Id { get; }
        public global::SpacetimeDB.Col<ItemDef, string> Name { get; }
        public global::SpacetimeDB.Col<ItemDef, string> ShortName { get; }
        public global::SpacetimeDB.Col<ItemDef, ItemKind> Kind { get; }
        public global::SpacetimeDB.Col<ItemDef, WeaponType> WeaponType { get; }
        public global::SpacetimeDB.Col<ItemDef, int> AtkBonus { get; }
        public global::SpacetimeDB.Col<ItemDef, int> DefenseBonus { get; }
        public global::SpacetimeDB.Col<ItemDef, int> StrengthBonus { get; }
        public global::SpacetimeDB.Col<ItemDef, int> DexterityBonus { get; }
        public global::SpacetimeDB.Col<ItemDef, int> IntelligenceBonus { get; }
        public global::SpacetimeDB.Col<ItemDef, int> SpeedBonus { get; }
        public global::SpacetimeDB.Col<ItemDef, int> MaxHpBonus { get; }
        public global::SpacetimeDB.Col<ItemDef, int> MaxManaBonus { get; }
        public global::SpacetimeDB.Col<ItemDef, int> HealAmount { get; }
        public global::SpacetimeDB.Col<ItemDef, int> ManaRestoreAmount { get; }
        public global::SpacetimeDB.Col<ItemDef, string> Description { get; }

        public ItemDefCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<ItemDef, uint>(tableName, "id");
            Name = new global::SpacetimeDB.Col<ItemDef, string>(tableName, "name");
            ShortName = new global::SpacetimeDB.Col<ItemDef, string>(tableName, "short_name");
            Kind = new global::SpacetimeDB.Col<ItemDef, ItemKind>(tableName, "kind");
            WeaponType = new global::SpacetimeDB.Col<ItemDef, WeaponType>(tableName, "weapon_type");
            AtkBonus = new global::SpacetimeDB.Col<ItemDef, int>(tableName, "atk_bonus");
            DefenseBonus = new global::SpacetimeDB.Col<ItemDef, int>(tableName, "defense_bonus");
            StrengthBonus = new global::SpacetimeDB.Col<ItemDef, int>(tableName, "strength_bonus");
            DexterityBonus = new global::SpacetimeDB.Col<ItemDef, int>(tableName, "dexterity_bonus");
            IntelligenceBonus = new global::SpacetimeDB.Col<ItemDef, int>(tableName, "intelligence_bonus");
            SpeedBonus = new global::SpacetimeDB.Col<ItemDef, int>(tableName, "speed_bonus");
            MaxHpBonus = new global::SpacetimeDB.Col<ItemDef, int>(tableName, "max_hp_bonus");
            MaxManaBonus = new global::SpacetimeDB.Col<ItemDef, int>(tableName, "max_mana_bonus");
            HealAmount = new global::SpacetimeDB.Col<ItemDef, int>(tableName, "heal_amount");
            ManaRestoreAmount = new global::SpacetimeDB.Col<ItemDef, int>(tableName, "mana_restore_amount");
            Description = new global::SpacetimeDB.Col<ItemDef, string>(tableName, "description");
        }
    }

    public sealed class ItemDefIxCols
    {
        public global::SpacetimeDB.IxCol<ItemDef, uint> Id { get; }

        public ItemDefIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<ItemDef, uint>(tableName, "id");
        }
    }
}
