// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PlayerHandle : RemoteTableHandle<EventContext, Player>
        {
            public override string RemoteTableName => "player";

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(Player row) => row.EntityId;

                public EntityIdUniqueIndex(PlayerHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            public sealed class IdentityUniqueIndex : UniqueIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(Player row) => row.Identity;

                public IdentityUniqueIndex(PlayerHandle table) : base(table) { }
            }

            public readonly IdentityUniqueIndex Identity;

            public sealed class SlotUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(Player row) => row.Slot;

                public SlotUniqueIndex(PlayerHandle table) : base(table) { }
            }

            public readonly SlotUniqueIndex Slot;

            internal PlayerHandle(DbConnection conn) : base(conn)
            {
                EntityId = new(this);
                Identity = new(this);
                Slot = new(this);
            }

            protected override object GetPrimaryKey(Player row) => row.Identity;
        }

        public readonly PlayerHandle Player;
    }

    public sealed class PlayerCols
    {
        public global::SpacetimeDB.Col<Player, SpacetimeDB.Identity> Identity { get; }
        public global::SpacetimeDB.Col<Player, uint> Slot { get; }
        public global::SpacetimeDB.Col<Player, bool> Online { get; }
        public global::SpacetimeDB.Col<Player, PlayerClass> Class { get; }
        public global::SpacetimeDB.Col<Player, ulong> EntityId { get; }

        public PlayerCols(string tableName)
        {
            Identity = new global::SpacetimeDB.Col<Player, SpacetimeDB.Identity>(tableName, "identity");
            Slot = new global::SpacetimeDB.Col<Player, uint>(tableName, "slot");
            Online = new global::SpacetimeDB.Col<Player, bool>(tableName, "online");
            Class = new global::SpacetimeDB.Col<Player, PlayerClass>(tableName, "class");
            EntityId = new global::SpacetimeDB.Col<Player, ulong>(tableName, "entity_id");
        }
    }

    public sealed class PlayerIxCols
    {
        public global::SpacetimeDB.IxCol<Player, SpacetimeDB.Identity> Identity { get; }
        public global::SpacetimeDB.IxCol<Player, uint> Slot { get; }
        public global::SpacetimeDB.IxCol<Player, ulong> EntityId { get; }

        public PlayerIxCols(string tableName)
        {
            Identity = new global::SpacetimeDB.IxCol<Player, SpacetimeDB.Identity>(tableName, "identity");
            Slot = new global::SpacetimeDB.IxCol<Player, uint>(tableName, "slot");
            EntityId = new global::SpacetimeDB.IxCol<Player, ulong>(tableName, "entity_id");
        }
    }
}
