// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class SkillDefHandle : RemoteTableHandle<EventContext, SkillDef>
        {
            public override string RemoteTableName => "skill_def";

            public sealed class IdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(SkillDef row) => row.Id;

                public IdUniqueIndex(SkillDefHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal SkillDefHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);

            }

            protected override object GetPrimaryKey(SkillDef row) => row.Id;
        }

        public readonly SkillDefHandle SkillDef;
    }

    public sealed class SkillDefCols
    {
        public global::SpacetimeDB.Col<SkillDef, uint> Id { get; }
        public global::SpacetimeDB.Col<SkillDef, string> Name { get; }
        public global::SpacetimeDB.Col<SkillDef, bool> IsEnemySkill { get; }
        public global::SpacetimeDB.Col<SkillDef, PlayerClass> Class { get; }
        public global::SpacetimeDB.Col<SkillDef, uint> UnlockFloor { get; }
        public global::SpacetimeDB.Col<SkillDef, uint> ManaCost { get; }
        public global::SpacetimeDB.Col<SkillDef, uint> BaseDamage { get; }
        public global::SpacetimeDB.Col<SkillDef, uint> TargetCount { get; }
        public global::SpacetimeDB.Col<SkillDef, bool> AlwaysGoFirst { get; }
        public global::SpacetimeDB.Col<SkillDef, uint> NextTurnStrengthBonus { get; }
        public global::SpacetimeDB.Col<SkillDef, uint> NextTurnSpeedOverride { get; }
        public global::SpacetimeDB.Col<SkillDef, DamageType> DamageType { get; }

        public SkillDefCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<SkillDef, uint>(tableName, "id");
            Name = new global::SpacetimeDB.Col<SkillDef, string>(tableName, "name");
            IsEnemySkill = new global::SpacetimeDB.Col<SkillDef, bool>(tableName, "is_enemy_skill");
            Class = new global::SpacetimeDB.Col<SkillDef, PlayerClass>(tableName, "class");
            UnlockFloor = new global::SpacetimeDB.Col<SkillDef, uint>(tableName, "unlock_floor");
            ManaCost = new global::SpacetimeDB.Col<SkillDef, uint>(tableName, "mana_cost");
            BaseDamage = new global::SpacetimeDB.Col<SkillDef, uint>(tableName, "base_damage");
            TargetCount = new global::SpacetimeDB.Col<SkillDef, uint>(tableName, "target_count");
            AlwaysGoFirst = new global::SpacetimeDB.Col<SkillDef, bool>(tableName, "always_go_first");
            NextTurnStrengthBonus = new global::SpacetimeDB.Col<SkillDef, uint>(tableName, "next_turn_strength_bonus");
            NextTurnSpeedOverride = new global::SpacetimeDB.Col<SkillDef, uint>(tableName, "next_turn_speed_override");
            DamageType = new global::SpacetimeDB.Col<SkillDef, DamageType>(tableName, "damage_type");
        }
    }

    public sealed class SkillDefIxCols
    {
        public global::SpacetimeDB.IxCol<SkillDef, uint> Id { get; }

        public SkillDefIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<SkillDef, uint>(tableName, "id");
        }
    }
}
