// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class TurnOrderHandle : RemoteTableHandle<EventContext, TurnOrder>
        {
            public override string RemoteTableName => "turn_order";

            public sealed class IdxUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(TurnOrder row) => row.Idx;

                public IdxUniqueIndex(TurnOrderHandle table) : base(table) { }
            }

            public readonly IdxUniqueIndex Idx;

            internal TurnOrderHandle(DbConnection conn) : base(conn)
            {
                Idx = new(this);
            }

            protected override object GetPrimaryKey(TurnOrder row) => row.Idx;
        }

        public readonly TurnOrderHandle TurnOrder;
    }

    public sealed class TurnOrderCols
    {
        public global::SpacetimeDB.Col<TurnOrder, uint> Idx { get; }
        public global::SpacetimeDB.Col<TurnOrder, ulong> EntityId { get; }
        public global::SpacetimeDB.Col<TurnOrder, int> Speed { get; }
        public global::SpacetimeDB.Col<TurnOrder, bool> HasActed { get; }
        public global::SpacetimeDB.Col<TurnOrder, bool> IsRush { get; }

        public TurnOrderCols(string tableName)
        {
            Idx = new global::SpacetimeDB.Col<TurnOrder, uint>(tableName, "idx");
            EntityId = new global::SpacetimeDB.Col<TurnOrder, ulong>(tableName, "entity_id");
            Speed = new global::SpacetimeDB.Col<TurnOrder, int>(tableName, "speed");
            HasActed = new global::SpacetimeDB.Col<TurnOrder, bool>(tableName, "has_acted");
            IsRush = new global::SpacetimeDB.Col<TurnOrder, bool>(tableName, "is_rush");
        }
    }

    public sealed class TurnOrderIxCols
    {
        public global::SpacetimeDB.IxCol<TurnOrder, uint> Idx { get; }

        public TurnOrderIxCols(string tableName)
        {
            Idx = new global::SpacetimeDB.IxCol<TurnOrder, uint>(tableName, "idx");
        }
    }
}
