// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class BossDrop
    {
        [DataMember(Name = "id")]
        public uint Id;
        [DataMember(Name = "tier")]
        public uint Tier;
        [DataMember(Name = "item_def_id")]
        public uint ItemDefId;

        public BossDrop(
            uint Id,
            uint Tier,
            uint ItemDefId
        )
        {
            this.Id = Id;
            this.Tier = Tier;
            this.ItemDefId = ItemDefId;
        }

        public BossDrop()
        {
        }
    }
}
