// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class CombatEvent
    {
        [DataMember(Name = "id")]
        public uint Id;
        [DataMember(Name = "round_number")]
        public uint RoundNumber;
        [DataMember(Name = "turn_number")]
        public uint TurnNumber;
        [DataMember(Name = "actor_kind")]
        public CombatantKind ActorKind;
        [DataMember(Name = "actor_id")]
        public uint ActorId;
        [DataMember(Name = "target_kind")]
        public CombatantKind TargetKind;
        [DataMember(Name = "target_id")]
        public uint TargetId;
        [DataMember(Name = "action_type")]
        public CombatActionType ActionType;
        [DataMember(Name = "skill_name")]
        public string SkillName;
        [DataMember(Name = "damage")]
        public uint Damage;
        [DataMember(Name = "healing")]
        public uint Healing;
        [DataMember(Name = "dodged")]
        public bool Dodged;
        [DataMember(Name = "clashed")]
        public bool Clashed;
        [DataMember(Name = "message")]
        public string Message;

        public CombatEvent(
            uint Id,
            uint RoundNumber,
            uint TurnNumber,
            CombatantKind ActorKind,
            uint ActorId,
            CombatantKind TargetKind,
            uint TargetId,
            CombatActionType ActionType,
            string SkillName,
            uint Damage,
            uint Healing,
            bool Dodged,
            bool Clashed,
            string Message
        )
        {
            this.Id = Id;
            this.RoundNumber = RoundNumber;
            this.TurnNumber = TurnNumber;
            this.ActorKind = ActorKind;
            this.ActorId = ActorId;
            this.TargetKind = TargetKind;
            this.TargetId = TargetId;
            this.ActionType = ActionType;
            this.SkillName = SkillName;
            this.Damage = Damage;
            this.Healing = Healing;
            this.Dodged = Dodged;
            this.Clashed = Clashed;
            this.Message = Message;
        }

        public CombatEvent()
        {
            this.SkillName = "";
            this.Message = "";
        }
    }
}
