// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Enemy
    {
        [DataMember(Name = "id")]
        public uint Id;
        [DataMember(Name = "slot")]
        public uint Slot;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "sprite_id")]
        public uint SpriteId;
        [DataMember(Name = "biome")]
        public Biome Biome;
        [DataMember(Name = "trait_name")]
        public string TraitName;
        [DataMember(Name = "is_boss")]
        public bool IsBoss;
        [DataMember(Name = "floor")]
        public uint Floor;
        [DataMember(Name = "max_health")]
        public uint MaxHealth;
        [DataMember(Name = "curr_health")]
        public uint CurrHealth;
        [DataMember(Name = "max_mana")]
        public uint MaxMana;
        [DataMember(Name = "curr_mana")]
        public uint CurrMana;
        [DataMember(Name = "speed")]
        public uint Speed;
        [DataMember(Name = "strength")]
        public uint Strength;
        [DataMember(Name = "dexterity")]
        public uint Dexterity;
        [DataMember(Name = "intelligence")]
        public uint Intelligence;
        [DataMember(Name = "atk")]
        public uint Atk;
        [DataMember(Name = "defense")]
        public uint Defense;
        [DataMember(Name = "strength_buff")]
        public uint StrengthBuff;
        [DataMember(Name = "next_turn_strength_bonus")]
        public uint NextTurnStrengthBonus;
        [DataMember(Name = "next_turn_speed_override")]
        public uint NextTurnSpeedOverride;
        [DataMember(Name = "go_first_next_round")]
        public bool GoFirstNextRound;
        [DataMember(Name = "alive")]
        public bool Alive;

        public Enemy(
            uint Id,
            uint Slot,
            string Name,
            uint SpriteId,
            Biome Biome,
            string TraitName,
            bool IsBoss,
            uint Floor,
            uint MaxHealth,
            uint CurrHealth,
            uint MaxMana,
            uint CurrMana,
            uint Speed,
            uint Strength,
            uint Dexterity,
            uint Intelligence,
            uint Atk,
            uint Defense,
            uint StrengthBuff,
            uint NextTurnStrengthBonus,
            uint NextTurnSpeedOverride,
            bool GoFirstNextRound,
            bool Alive
        )
        {
            this.Id = Id;
            this.Slot = Slot;
            this.Name = Name;
            this.SpriteId = SpriteId;
            this.Biome = Biome;
            this.TraitName = TraitName;
            this.IsBoss = IsBoss;
            this.Floor = Floor;
            this.MaxHealth = MaxHealth;
            this.CurrHealth = CurrHealth;
            this.MaxMana = MaxMana;
            this.CurrMana = CurrMana;
            this.Speed = Speed;
            this.Strength = Strength;
            this.Dexterity = Dexterity;
            this.Intelligence = Intelligence;
            this.Atk = Atk;
            this.Defense = Defense;
            this.StrengthBuff = StrengthBuff;
            this.NextTurnStrengthBonus = NextTurnStrengthBonus;
            this.NextTurnSpeedOverride = NextTurnSpeedOverride;
            this.GoFirstNextRound = GoFirstNextRound;
            this.Alive = Alive;
        }

        public Enemy()
        {
            this.Name = "";
            this.TraitName = "";
        }
    }
}
