// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class EnemySkill
    {
        [DataMember(Name = "id")]
        public uint Id;
        [DataMember(Name = "enemy_id")]
        public uint EnemyId;
        [DataMember(Name = "skill_def_id")]
        public uint SkillDefId;

        public EnemySkill(
            uint Id,
            uint EnemyId,
            uint SkillDefId
        )
        {
            this.Id = Id;
            this.EnemyId = EnemyId;
            this.SkillDefId = SkillDefId;
        }

        public EnemySkill()
        {
        }
    }
}
