// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class EntitySkill
    {
        [DataMember(Name = "id")]
        public uint Id;
        [DataMember(Name = "entity_id")]
        public ulong EntityId;
        [DataMember(Name = "skill_def_id")]
        public uint SkillDefId;

        public EntitySkill(
            uint Id,
            ulong EntityId,
            uint SkillDefId
        )
        {
            this.Id = Id;
            this.EntityId = EntityId;
            this.SkillDefId = SkillDefId;
        }

        public EntitySkill()
        {

        }
    }
}
