// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Entity
    {
        [DataMember(Name = "entity_id")]
        public ulong EntityId;
        [DataMember(Name = "faction")]
        public Team Faction;
        [DataMember(Name = "slot")]
        public uint Slot;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "class_name")]
        public string ClassName;
        [DataMember(Name = "max_hp")]
        public int MaxHp;
        [DataMember(Name = "hp")]
        public int Hp;
        [DataMember(Name = "max_mana")]
        public int MaxMana;
        [DataMember(Name = "mana")]
        public int Mana;
        [DataMember(Name = "strength")]
        public int Strength;
        [DataMember(Name = "damage")]
        public int Damage;
        [DataMember(Name = "speed")]
        public int Speed;
        [DataMember(Name = "alive")]
        public bool Alive;
        [DataMember(Name = "potions")]
        public int Potions;
        [DataMember(Name = "skill_name")]
        public string SkillName;
        [DataMember(Name = "skill_atk")]
        public int SkillAtk;
        [DataMember(Name = "skill_mana_cost")]
        public int SkillManaCost;

        public Entity(
            ulong EntityId,
            Team Faction,
            uint Slot,
            string Name,
            string ClassName,
            int MaxHp,
            int Hp,
            int MaxMana,
            int Mana,
            int Strength,
            int Damage,
            int Speed,
            bool Alive,
            int Potions,
            string SkillName,
            int SkillAtk,
            int SkillManaCost
        )
        {
            this.EntityId = EntityId;
            this.Faction = Faction;
            this.Slot = Slot;
            this.Name = Name;
            this.ClassName = ClassName;
            this.MaxHp = MaxHp;
            this.Hp = Hp;
            this.MaxMana = MaxMana;
            this.Mana = Mana;
            this.Strength = Strength;
            this.Damage = Damage;
            this.Speed = Speed;
            this.Alive = Alive;
            this.Potions = Potions;
            this.SkillName = SkillName;
            this.SkillAtk = SkillAtk;
            this.SkillManaCost = SkillManaCost;
        }

        public Entity()
        {
            this.Name = "";
            this.ClassName = "";
            this.SkillName = "";
        }
    }
}
