// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Entity
    {
        [DataMember(Name = "entity_id")]
        public ulong EntityId;
        [DataMember(Name = "faction")]
        public Team Faction;
        [DataMember(Name = "slot")]
        public uint Slot;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "class_name")]
        public string ClassName;
        [DataMember(Name = "max_hp")]
        public int MaxHp;
        [DataMember(Name = "hp")]
        public int Hp;
        [DataMember(Name = "max_mana")]
        public int MaxMana;
        [DataMember(Name = "mana")]
        public int Mana;
        [DataMember(Name = "base_strength")]
        public int BaseStrength;
        [DataMember(Name = "base_dexterity")]
        public int BaseDexterity;
        [DataMember(Name = "base_intelligence")]
        public int BaseIntelligence;
        [DataMember(Name = "base_speed")]
        public int BaseSpeed;
        [DataMember(Name = "strength")]
        public int Strength;
        [DataMember(Name = "dexterity")]
        public int Dexterity;
        [DataMember(Name = "intelligence")]
        public int Intelligence;
        [DataMember(Name = "speed")]
        public int Speed;
        [DataMember(Name = "atk")]
        public int Atk;
        [DataMember(Name = "defense")]
        public int Defense;
        [DataMember(Name = "strength_buff")]
        public int StrengthBuff;
        [DataMember(Name = "next_turn_strength_bonus")]
        public int NextTurnStrengthBonus;
        [DataMember(Name = "go_first_next_round")]
        public bool GoFirstNextRound;
        [DataMember(Name = "alive")]
        public bool Alive;
        [DataMember(Name = "basic_attack_name")]
        public string BasicAttackName;
        [DataMember(Name = "burn_stack")]
        public int BurnStack;
        [DataMember(Name = "burn_count")]
        public int BurnCount;
        [DataMember(Name = "weak_stacks")]
        public int WeakStacks;
        [DataMember(Name = "next_turn_weak")]
        public int NextTurnWeak;
        [DataMember(Name = "fragile_stacks")]
        public int FragileStacks;
        [DataMember(Name = "next_turn_fragile")]
        public int NextTurnFragile;
        [DataMember(Name = "combat_speed")]
        public int CombatSpeed;
        [DataMember(Name = "next_turn_speed_set")]
        public int NextTurnSpeedSet;
        [DataMember(Name = "next_turn_speed_delta")]
        public int NextTurnSpeedDelta;
        [DataMember(Name = "dodge_bonus_percent")]
        public int DodgeBonusPercent;
        [DataMember(Name = "next_turn_dodge_bonus")]
        public int NextTurnDodgeBonus;
        [DataMember(Name = "evade_threshold")]
        public int EvadeThreshold;
        [DataMember(Name = "evade_fragile_on_dodge")]
        public int EvadeFragileOnDodge;
        [DataMember(Name = "evade_strength_on_dodge")]
        public int EvadeStrengthOnDodge;
        [DataMember(Name = "has_dodged")]
        public bool HasDodged;
        [DataMember(Name = "used_attack_this_turn")]
        public bool UsedAttackThisTurn;
        [DataMember(Name = "used_attack_last_turn")]
        public bool UsedAttackLastTurn;
        [DataMember(Name = "next_attack_bonus")]
        public int NextAttackBonus;
        [DataMember(Name = "magic_bullet_stage")]
        public int MagicBulletStage;
        [DataMember(Name = "spear_discount")]
        public int SpearDiscount;
        [DataMember(Name = "vertical_cut_discount")]
        public int VerticalCutDiscount;
        [DataMember(Name = "finish_the_job_used")]
        public bool FinishTheJobUsed;
        [DataMember(Name = "finish_the_job_stance")]
        public bool FinishTheJobStance;
        [DataMember(Name = "finish_the_job_power")]
        public int FinishTheJobPower;
        [DataMember(Name = "necromancy_used")]
        public bool NecromancyUsed;
        [DataMember(Name = "skip_next_turn")]
        public bool SkipNextTurn;
        [DataMember(Name = "grand_undertaking_pending")]
        public bool GrandUndertakingPending;
        [DataMember(Name = "variant_prefix")]
        public string VariantPrefix;
        [DataMember(Name = "tint_r")]
        public int TintR;
        [DataMember(Name = "tint_g")]
        public int TintG;
        [DataMember(Name = "tint_b")]
        public int TintB;
        [DataMember(Name = "is_boss")]
        public bool IsBoss;
        [DataMember(Name = "skill_cooldown")]
        public int SkillCooldown;

        public Entity(
            ulong EntityId,
            Team Faction,
            uint Slot,
            string Name,
            string ClassName,
            int MaxHp,
            int Hp,
            int MaxMana,
            int Mana,
            int BaseStrength,
            int BaseDexterity,
            int BaseIntelligence,
            int BaseSpeed,
            int Strength,
            int Dexterity,
            int Intelligence,
            int Speed,
            int Atk,
            int Defense,
            int StrengthBuff,
            int NextTurnStrengthBonus,
            bool GoFirstNextRound,
            bool Alive,
            string BasicAttackName,
            int BurnStack,
            int BurnCount,
            int WeakStacks,
            int NextTurnWeak,
            int FragileStacks,
            int NextTurnFragile,
            int CombatSpeed,
            int NextTurnSpeedSet,
            int NextTurnSpeedDelta,
            int DodgeBonusPercent,
            int NextTurnDodgeBonus,
            int EvadeThreshold,
            int EvadeFragileOnDodge,
            int EvadeStrengthOnDodge,
            bool HasDodged,
            bool UsedAttackThisTurn,
            bool UsedAttackLastTurn,
            int NextAttackBonus,
            int MagicBulletStage,
            int SpearDiscount,
            int VerticalCutDiscount,
            bool FinishTheJobUsed,
            bool FinishTheJobStance,
            int FinishTheJobPower,
            bool NecromancyUsed,
            bool SkipNextTurn,
            bool GrandUndertakingPending,
            string VariantPrefix,
            int TintR,
            int TintG,
            int TintB,
            bool IsBoss,
            int SkillCooldown
        )
        {
            this.EntityId = EntityId;
            this.Faction = Faction;
            this.Slot = Slot;
            this.Name = Name;
            this.ClassName = ClassName;
            this.MaxHp = MaxHp;
            this.Hp = Hp;
            this.MaxMana = MaxMana;
            this.Mana = Mana;
            this.BaseStrength = BaseStrength;
            this.BaseDexterity = BaseDexterity;
            this.BaseIntelligence = BaseIntelligence;
            this.BaseSpeed = BaseSpeed;
            this.Strength = Strength;
            this.Dexterity = Dexterity;
            this.Intelligence = Intelligence;
            this.Speed = Speed;
            this.Atk = Atk;
            this.Defense = Defense;
            this.StrengthBuff = StrengthBuff;
            this.NextTurnStrengthBonus = NextTurnStrengthBonus;
            this.GoFirstNextRound = GoFirstNextRound;
            this.Alive = Alive;
            this.BasicAttackName = BasicAttackName;
            this.BurnStack = BurnStack;
            this.BurnCount = BurnCount;
            this.WeakStacks = WeakStacks;
            this.NextTurnWeak = NextTurnWeak;
            this.FragileStacks = FragileStacks;
            this.NextTurnFragile = NextTurnFragile;
            this.CombatSpeed = CombatSpeed;
            this.NextTurnSpeedSet = NextTurnSpeedSet;
            this.NextTurnSpeedDelta = NextTurnSpeedDelta;
            this.DodgeBonusPercent = DodgeBonusPercent;
            this.NextTurnDodgeBonus = NextTurnDodgeBonus;
            this.EvadeThreshold = EvadeThreshold;
            this.EvadeFragileOnDodge = EvadeFragileOnDodge;
            this.EvadeStrengthOnDodge = EvadeStrengthOnDodge;
            this.HasDodged = HasDodged;
            this.UsedAttackThisTurn = UsedAttackThisTurn;
            this.UsedAttackLastTurn = UsedAttackLastTurn;
            this.NextAttackBonus = NextAttackBonus;
            this.MagicBulletStage = MagicBulletStage;
            this.SpearDiscount = SpearDiscount;
            this.VerticalCutDiscount = VerticalCutDiscount;
            this.FinishTheJobUsed = FinishTheJobUsed;
            this.FinishTheJobStance = FinishTheJobStance;
            this.FinishTheJobPower = FinishTheJobPower;
            this.NecromancyUsed = NecromancyUsed;
            this.SkipNextTurn = SkipNextTurn;
            this.GrandUndertakingPending = GrandUndertakingPending;
            this.VariantPrefix = VariantPrefix;
            this.TintR = TintR;
            this.TintG = TintG;
            this.TintB = TintB;
            this.IsBoss = IsBoss;
            this.SkillCooldown = SkillCooldown;
        }

        public Entity()
        {
            this.Name = "";
            this.ClassName = "";
            this.BasicAttackName = "";
            this.VariantPrefix = "";
        }
    }
}
