// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class GameSession
    {
        [DataMember(Name = "id")]
        public uint Id;
        [DataMember(Name = "player_count")]
        public uint PlayerCount;
        [DataMember(Name = "max_players")]
        public uint MaxPlayers;
        [DataMember(Name = "phase")]
        public BattlePhase Phase;
        [DataMember(Name = "round")]
        public uint Round;
        [DataMember(Name = "turn_index")]
        public uint TurnIndex;
        [DataMember(Name = "active_entity_id")]
        public ulong ActiveEntityId;
        [DataMember(Name = "stage_number")]
        public uint StageNumber;
        [DataMember(Name = "upcoming_rest_stop")]
        public bool UpcomingRestStop;
        [DataMember(Name = "attack_redirect_entity_id")]
        public ulong AttackRedirectEntityId;
        [DataMember(Name = "current_biome")]
        public WorldBiome CurrentBiome;
        [DataMember(Name = "next_biome")]
        public WorldBiome NextBiome;

        public GameSession(
            uint Id,
            uint PlayerCount,
            uint MaxPlayers,
            BattlePhase Phase,
            uint Round,
            uint TurnIndex,
            ulong ActiveEntityId,
            uint StageNumber,
            bool UpcomingRestStop,
            ulong AttackRedirectEntityId,
            WorldBiome CurrentBiome,
            WorldBiome NextBiome
        )
        {
            this.Id = Id;
            this.PlayerCount = PlayerCount;
            this.MaxPlayers = MaxPlayers;
            this.Phase = Phase;
            this.Round = Round;
            this.TurnIndex = TurnIndex;
            this.ActiveEntityId = ActiveEntityId;
            this.StageNumber = StageNumber;
            this.UpcomingRestStop = UpcomingRestStop;
            this.AttackRedirectEntityId = AttackRedirectEntityId;
            this.CurrentBiome = CurrentBiome;
            this.NextBiome = NextBiome;
        }

        public GameSession()
        {
        }
    }
}
