// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ItemDef
    {
        [DataMember(Name = "id")]
        public uint Id;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "kind")]
        public ItemKind Kind;
        [DataMember(Name = "weapon_type")]
        public WeaponType WeaponType;
        [DataMember(Name = "armor_slot")]
        public ArmorSlot ArmorSlot;
        [DataMember(Name = "atk_bonus")]
        public uint AtkBonus;
        [DataMember(Name = "strength_bonus")]
        public uint StrengthBonus;
        [DataMember(Name = "dexterity_bonus")]
        public uint DexterityBonus;
        [DataMember(Name = "intelligence_bonus")]
        public uint IntelligenceBonus;
        [DataMember(Name = "speed_bonus")]
        public uint SpeedBonus;
        [DataMember(Name = "max_health_bonus")]
        public uint MaxHealthBonus;
        [DataMember(Name = "max_mana_bonus")]
        public uint MaxManaBonus;
        [DataMember(Name = "heal_amount")]
        public uint HealAmount;
        [DataMember(Name = "mana_restore_amount")]
        public uint ManaRestoreAmount;
        [DataMember(Name = "sprite_id")]
        public uint SpriteId;

        public ItemDef(
            uint Id,
            string Name,
            ItemKind Kind,
            WeaponType WeaponType,
            ArmorSlot ArmorSlot,
            uint AtkBonus,
            uint StrengthBonus,
            uint DexterityBonus,
            uint IntelligenceBonus,
            uint SpeedBonus,
            uint MaxHealthBonus,
            uint MaxManaBonus,
            uint HealAmount,
            uint ManaRestoreAmount,
            uint SpriteId
        )
        {
            this.Id = Id;
            this.Name = Name;
            this.Kind = Kind;
            this.WeaponType = WeaponType;
            this.ArmorSlot = ArmorSlot;
            this.AtkBonus = AtkBonus;
            this.StrengthBonus = StrengthBonus;
            this.DexterityBonus = DexterityBonus;
            this.IntelligenceBonus = IntelligenceBonus;
            this.SpeedBonus = SpeedBonus;
            this.MaxHealthBonus = MaxHealthBonus;
            this.MaxManaBonus = MaxManaBonus;
            this.HealAmount = HealAmount;
            this.ManaRestoreAmount = ManaRestoreAmount;
            this.SpriteId = SpriteId;
        }

        public ItemDef()
        {
            this.Name = "";
        }
    }
}
