// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PendingReward
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "owner")]
        public SpacetimeDB.Identity Owner;
        [DataMember(Name = "item_def_id")]
        public uint ItemDefId;

        public PendingReward(
            ulong Id,
            SpacetimeDB.Identity Owner,
            uint ItemDefId
        )
        {
            this.Id = Id;
            this.Owner = Owner;
            this.ItemDefId = ItemDefId;
        }

        public PendingReward()
        {
        }
    }
}
