// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PlayerItem
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "owner")]
        public SpacetimeDB.Identity Owner;
        [DataMember(Name = "item_def_id")]
        public uint ItemDefId;
        [DataMember(Name = "quantity")]
        public int Quantity;
        [DataMember(Name = "equipped_slot")]
        public EquipSlot EquippedSlot;
        [DataMember(Name = "inventory_index")]
        public uint InventoryIndex;

        public PlayerItem(
            ulong Id,
            SpacetimeDB.Identity Owner,
            uint ItemDefId,
            int Quantity,
            EquipSlot EquippedSlot,
            uint InventoryIndex
        )
        {
            this.Id = Id;
            this.Owner = Owner;
            this.ItemDefId = ItemDefId;
            this.Quantity = Quantity;
            this.EquippedSlot = EquippedSlot;
            this.InventoryIndex = InventoryIndex;
        }

        public PlayerItem()
        {
        }
    }
}
