// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PlayerItem
    {
        [DataMember(Name = "id")]
        public uint Id;
        [DataMember(Name = "owner")]
        public SpacetimeDB.Identity Owner;
        [DataMember(Name = "item_def_id")]
        public uint ItemDefId;
        [DataMember(Name = "quantity")]
        public uint Quantity;
        [DataMember(Name = "equipped_slot")]
        public EquipSlot EquippedSlot;

        public PlayerItem(
            uint Id,
            SpacetimeDB.Identity Owner,
            uint ItemDefId,
            uint Quantity,
            EquipSlot EquippedSlot
        )
        {
            this.Id = Id;
            this.Owner = Owner;
            this.ItemDefId = ItemDefId;
            this.Quantity = Quantity;
            this.EquippedSlot = EquippedSlot;
        }

        public PlayerItem()
        {
        }
    }
}
