// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Player
    {
        [DataMember(Name = "identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "slot")]
        public uint Slot;
        [DataMember(Name = "online")]
        public bool Online;
        [DataMember(Name = "class")]
        public PlayerClass Class;
        [DataMember(Name = "max_health_points")]
        public uint MaxHealthPoints;
        [DataMember(Name = "curr_health_points")]
        public uint CurrHealthPoints;
        [DataMember(Name = "max_mana")]
        public uint MaxMana;
        [DataMember(Name = "curr_mana")]
        public uint CurrMana;
        [DataMember(Name = "speed")]
        public uint Speed;
        [DataMember(Name = "strength")]
        public uint Strength;
        [DataMember(Name = "dexterity")]
        public uint Dexterity;
        [DataMember(Name = "intelligence")]
        public uint Intelligence;

        public Player(
            SpacetimeDB.Identity Identity,
            uint Slot,
            bool Online,
            PlayerClass Class,
            uint MaxHealthPoints,
            uint CurrHealthPoints,
            uint MaxMana,
            uint CurrMana,
            uint Speed,
            uint Strength,
            uint Dexterity,
            uint Intelligence
        )
        {
            this.Identity = Identity;
            this.Slot = Slot;
            this.Online = Online;
            this.Class = Class;
            this.MaxHealthPoints = MaxHealthPoints;
            this.CurrHealthPoints = CurrHealthPoints;
            this.MaxMana = MaxMana;
            this.CurrMana = CurrMana;
            this.Speed = Speed;
            this.Strength = Strength;
            this.Dexterity = Dexterity;
            this.Intelligence = Intelligence;
        }

        public Player()
        {
        }
    }
}
