// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Player
    {
        [DataMember(Name = "identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "slot")]
        public uint Slot;
        [DataMember(Name = "online")]
        public bool Online;
        [DataMember(Name = "class")]
        public PlayerClass Class;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "sprite_id")]
        public uint SpriteId;
        [DataMember(Name = "level")]
        public uint Level;
        [DataMember(Name = "xp")]
        public uint Xp;
        [DataMember(Name = "unspent_stat_points")]
        public uint UnspentStatPoints;
        [DataMember(Name = "max_health")]
        public uint MaxHealth;
        [DataMember(Name = "curr_health")]
        public uint CurrHealth;
        [DataMember(Name = "max_mana")]
        public uint MaxMana;
        [DataMember(Name = "curr_mana")]
        public uint CurrMana;
        [DataMember(Name = "speed")]
        public uint Speed;
        [DataMember(Name = "strength")]
        public uint Strength;
        [DataMember(Name = "dexterity")]
        public uint Dexterity;
        [DataMember(Name = "intelligence")]
        public uint Intelligence;
        [DataMember(Name = "base_speed")]
        public uint BaseSpeed;
        [DataMember(Name = "base_strength")]
        public uint BaseStrength;
        [DataMember(Name = "base_dexterity")]
        public uint BaseDexterity;
        [DataMember(Name = "base_intelligence")]
        public uint BaseIntelligence;
        [DataMember(Name = "atk")]
        public uint Atk;
        [DataMember(Name = "base_defense")]
        public uint BaseDefense;
        [DataMember(Name = "defense")]
        public uint Defense;
        [DataMember(Name = "strength_buff")]
        public uint StrengthBuff;
        [DataMember(Name = "next_turn_strength_bonus")]
        public uint NextTurnStrengthBonus;
        [DataMember(Name = "next_turn_speed_override")]
        public uint NextTurnSpeedOverride;
        [DataMember(Name = "go_first_next_round")]
        public bool GoFirstNextRound;
        [DataMember(Name = "is_defending")]
        public bool IsDefending;
        [DataMember(Name = "alive")]
        public bool Alive;
        [DataMember(Name = "equipped_weapon_def_id")]
        public uint EquippedWeaponDefId;
        [DataMember(Name = "equipped_helmet_def_id")]
        public uint EquippedHelmetDefId;
        [DataMember(Name = "equipped_chestplate_def_id")]
        public uint EquippedChestplateDefId;
        [DataMember(Name = "equipped_leggings_def_id")]
        public uint EquippedLeggingsDefId;
        [DataMember(Name = "equipped_boots_def_id")]
        public uint EquippedBootsDefId;

        public Player(
            SpacetimeDB.Identity Identity,
            uint Slot,
            bool Online,
            PlayerClass Class,
            string Name,
            uint SpriteId,
            uint Level,
            uint Xp,
            uint UnspentStatPoints,
            uint MaxHealth,
            uint CurrHealth,
            uint MaxMana,
            uint CurrMana,
            uint Speed,
            uint Strength,
            uint Dexterity,
            uint Intelligence,
            uint BaseSpeed,
            uint BaseStrength,
            uint BaseDexterity,
            uint BaseIntelligence,
            uint Atk,
            uint BaseDefense,
            uint Defense,
            uint StrengthBuff,
            uint NextTurnStrengthBonus,
            uint NextTurnSpeedOverride,
            bool GoFirstNextRound,
            bool IsDefending,
            bool Alive,
            uint EquippedWeaponDefId,
            uint EquippedHelmetDefId,
            uint EquippedChestplateDefId,
            uint EquippedLeggingsDefId,
            uint EquippedBootsDefId
        )
        {
            this.Identity = Identity;
            this.Slot = Slot;
            this.Online = Online;
            this.Class = Class;
            this.Name = Name;
            this.SpriteId = SpriteId;
            this.Level = Level;
            this.Xp = Xp;
            this.UnspentStatPoints = UnspentStatPoints;
            this.MaxHealth = MaxHealth;
            this.CurrHealth = CurrHealth;
            this.MaxMana = MaxMana;
            this.CurrMana = CurrMana;
            this.Speed = Speed;
            this.Strength = Strength;
            this.Dexterity = Dexterity;
            this.Intelligence = Intelligence;
            this.BaseSpeed = BaseSpeed;
            this.BaseStrength = BaseStrength;
            this.BaseDexterity = BaseDexterity;
            this.BaseIntelligence = BaseIntelligence;
            this.Atk = Atk;
            this.BaseDefense = BaseDefense;
            this.Defense = Defense;
            this.StrengthBuff = StrengthBuff;
            this.NextTurnStrengthBonus = NextTurnStrengthBonus;
            this.NextTurnSpeedOverride = NextTurnSpeedOverride;
            this.GoFirstNextRound = GoFirstNextRound;
            this.IsDefending = IsDefending;
            this.Alive = Alive;
            this.EquippedWeaponDefId = EquippedWeaponDefId;
            this.EquippedHelmetDefId = EquippedHelmetDefId;
            this.EquippedChestplateDefId = EquippedChestplateDefId;
            this.EquippedLeggingsDefId = EquippedLeggingsDefId;
            this.EquippedBootsDefId = EquippedBootsDefId;
        }

        public Player()
        {
            this.Name = "";
        }
    }
}
