// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class SkillDef
    {
        [DataMember(Name = "id")]
        public uint Id;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "is_enemy_skill")]
        public bool IsEnemySkill;
        [DataMember(Name = "class")]
        public PlayerClass Class;
        [DataMember(Name = "biome")]
        public Biome Biome;
        [DataMember(Name = "unlock_floor")]
        public uint UnlockFloor;
        [DataMember(Name = "mana_cost")]
        public uint ManaCost;
        [DataMember(Name = "base_damage")]
        public uint BaseDamage;
        [DataMember(Name = "target_count")]
        public uint TargetCount;
        [DataMember(Name = "always_go_first")]
        public bool AlwaysGoFirst;
        [DataMember(Name = "next_turn_strength_bonus")]
        public uint NextTurnStrengthBonus;
        [DataMember(Name = "next_turn_speed_override")]
        public uint NextTurnSpeedOverride;
        [DataMember(Name = "damage_type")]
        public DamageType DamageType;

        public SkillDef(
            uint Id,
            string Name,
            bool IsEnemySkill,
            PlayerClass Class,
            Biome Biome,
            uint UnlockFloor,
            uint ManaCost,
            uint BaseDamage,
            uint TargetCount,
            bool AlwaysGoFirst,
            uint NextTurnStrengthBonus,
            uint NextTurnSpeedOverride,
            DamageType DamageType
        )
        {
            this.Id = Id;
            this.Name = Name;
            this.IsEnemySkill = IsEnemySkill;
            this.Class = Class;
            this.Biome = Biome;
            this.UnlockFloor = UnlockFloor;
            this.ManaCost = ManaCost;
            this.BaseDamage = BaseDamage;
            this.TargetCount = TargetCount;
            this.AlwaysGoFirst = AlwaysGoFirst;
            this.NextTurnStrengthBonus = NextTurnStrengthBonus;
            this.NextTurnSpeedOverride = NextTurnSpeedOverride;
            this.DamageType = DamageType;
        }

        public SkillDef()
        {
            this.Name = "";
        }
    }
}
