// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class TurnOrder
    {
        [DataMember(Name = "id")]
        public uint Id;
        [DataMember(Name = "sequence")]
        public uint Sequence;
        [DataMember(Name = "kind")]
        public CombatantKind Kind;
        [DataMember(Name = "combatant_id")]
        public uint CombatantId;
        [DataMember(Name = "speed")]
        public uint Speed;
        [DataMember(Name = "has_acted")]
        public bool HasActed;
        [DataMember(Name = "is_rush")]
        public bool IsRush;

        public TurnOrder(
            uint Id,
            uint Sequence,
            CombatantKind Kind,
            uint CombatantId,
            uint Speed,
            bool HasActed,
            bool IsRush
        )
        {
            this.Id = Id;
            this.Sequence = Sequence;
            this.Kind = Kind;
            this.CombatantId = CombatantId;
            this.Speed = Speed;
            this.HasActed = HasActed;
            this.IsRush = IsRush;
        }

        public TurnOrder()
        {
        }
    }
}
