// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class TurnOrder
    {
        [DataMember(Name = "idx")]
        public uint Idx;
        [DataMember(Name = "entity_id")]
        public ulong EntityId;

        public TurnOrder(
            uint Idx,
            ulong EntityId
        )
        {
            this.Idx = Idx;
            this.EntityId = EntityId;
        }

        public TurnOrder()
        {
        }
    }
}
